In [30]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\lenovo\onedrive\onedrive - national college of ireland\machine_learning_project\.venv\lib\site-packages (3.1.0)
Requirement already satisfied: numpy>=2.0.2 in c:\users\lenovo\onedrive\onedrive - national college of ireland\machine_learning_project\.venv\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.9.0 in c:\users\lenovo\onedrive\onedrive - national college of ireland\machine_learning_project\.venv\lib\site-packages (from pandas) (3.0.0)
Requirement already satisfied: tzdata in c:\users\lenovo\onedrive\onedrive - national college of ireland\machine_learning_project\.venv\lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.6 in c:\users\lenovo\onedrive\onedrive - national college of ireland\machine_learning_project\.venv\lib\site-packages (from python-dateutil>=2.9.0->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [48]:
# lets Connect to the data folder
import pandas as pd
file_path = r'C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\raw_dataset\Housing_dataset\Housing-BER Research Tool\BERPublicsearch.txt'
pd.set_option('display.max_columns', None) #Seting up this because this is a lot of data and i wanted to see all the columns

In [49]:
# Open the file and read only the first line (the column names)
f = open(file_path, 'r', encoding='latin-1')
first_line = f.readline()
f.close()

# Print all the First_line basically the columns
print(first_line)

CountyName	DwellingTypeDescr	Year_of_Construction	TypeofRating	EnergyRating	BerRating	GroundFloorArea(sq m)	UValueWall	UValueRoof	UValueFloor	UValueWindow	UvalueDoor	WallArea	RoofArea	FloorArea	WindowArea	DoorArea	NoStoreys	CO2Rating	MainSpaceHeatingFuel	MainWaterHeatingFuel	HSMainSystemEfficiency	MultiDwellingMPRN	TGDLEdition	MPCDERValue	HSEffAdjFactor	HSSupplHeatFraction	HSSupplSystemEff	WHMainSystemEff	WHEffAdjFactor	SupplSHFuel	SupplWHFuel	SHRenewableResources	WHRenewableResources	NoOfChimneys	NoOfOpenFlues	NoOfFansAndVents	NoOfFluelessGasFires	DraftLobby	VentilationMethod	FanPowerManuDeclaredValue	HeatExchangerEff	StructureType	SuspendedWoodenFloor	PercentageDraughtStripped	NoOfSidesSheltered	PermeabilityTest	PermeabilityTestResult	TempAdjustment	HeatSystemControlCat	HeatSystemResponseCat	NoCentralHeatingPumps	CHBoilerThermostatControlled	NoOilBoilerHeatingPumps	OBBoilerThermostatControlled	OBPumpInsideDwelling	NoGasBoilerHeatingPumps	WarmAirHeatingSystem	UndergroundHeating	GroundFloorUValue	StorageLosses	ManuLossFactorAvail	SolarHotWaterHeating	ElecImmersionInSummer	CombiBoiler	KeepHotFacility	WaterStorageVolume	DeclaredLossFactor	TempFactorUnadj	TempFactorMultiplier	InsulationType	InsulationThickness	PrimaryCircuitLoss	CombiBoilerAddLoss	ElecConsumpKeepHot	ApertureArea	ZeroLossCollectorEff	CollectorHeatLossCoEff	AnnualSolarRadiation	OvershadingFactor	CylinderStat	SolarStorageVolume	VolumeOfPreHeatStore	CombinedCylinder	ElectricityConsumption	SWHPumpSolarPowered	ChargingBasisHeatConsumed	gsdHSSupplHeatFraction	gsdHSSupplSystemEff	DistLossFactor	CHPUnitHeatFraction	CHPSystemType	CHPSystemTypeDescription	GroupHeatingCO2EQEmissionsFactor	GroupHeatingNonRenewablePEF	GroupHeatingRenewablePEF	HeatLossFromDistributionSystemOutsideDwelling	CHPElecEff	CHPHeatEff	CHPFuelType	SupplHSFuelTypeID	gsdSHRenewableResources	gsdWHRenewableResources	SolarHeatFraction	GroundFloorArea	GroundFloorHeight	FirstFloorArea	FirstFloorHeight	SecondFloorArea	SecondFloorHeight	ThirdFloorArea	ThirdFloorHeight	ThermalBridgingFactor	ThermalMassCategory	PredominantRoofTypeArea	PredominantRoofType	LivingAreaPercent	RoomInRoofArea	PurposeOfRating	DateOfAssessment	FirstEnergyTypeId	FirstEnergyType_Description	FirstEnerProdComment	FirstEnerProdDelivered	FirstPartLTotalContribution	FirstEnerProdConvFactor	FirstEnerProdCO2EmissionFactor	FirstEnerConsumedComment	FirstEnerConsumedDelivered	FirstEnerConsumedConvFactor	FirstEnerConsumedCO2EmissionFactor	SecondEnergyTypeId	SecondEnergyType_Description	SecondEnerProdComment	SecondEnerProdDelivered	SecondPartLTotalContribution	SecondEnerProdConvFactor	SecondEnerProdCO2EmissionFactor	SecondEnerConsumedComment	SecondEnerConsumedDelivered	SecondEnerConsumedConvFactor	SecondEnerConsumedCO2EmissionFactor	ThirdEnergyTypeId	ThirdEnergyType_Description	ThirdEnerProdComment	ThirdEnerProdDelivered	ThirdPartLTotalContribution	ThirdEnerProdConvFactor	ThirdEnerProdCO2EmissionFactor	ThirdEnerConsumedComment	ThirdEnerConsumedDelivered	ThirdEnerConsumedConvFactor	ThirdEnerConsumedCO2EmissionFactor	FirstBoilerFuelType	FirstHeatGenPlantEff	FirstPercentageHeat	SecondBoilerFuelType	SecondHeatGenPlantEff	SecondPercentageHeat	ThirdBoilerFuelType	ThirdHeatGenPlantEff	ThirdPercentageHeat	SolarSpaceHeatingSystem	FirstWallType_Description	FirstWallDescription	FirstWallArea	FirstWallUValue	FirstWallIsSemiExposed	FirstWallAgeBandId	FirstWallTypeId	SecondWallType_Description	SecondWallDescription	SecondWallArea	SecondWallUValue	SecondWallIsSemiExposed	SecondWallAgeBandId	SecondWallTypeId	ThirdWallType_Description	ThirdWallDescription	ThirdWallArea	ThirdWallUValue	ThirdWallIsSemiExposed	ThirdWallAgeBandId	ThirdWallTypeId	SA_Code	prob_smarea_error_0corr	prob_smarea_error_100corr	RER	RenewEPnren	RenewEPren	CPC	EPC	CapacityToWorkAtLowTemperatureLevels	SolarWaterHeatingOrientation	SolarWaterHeatingTiltInDegreesFromHorizontal	SolarWaterHeatingOvershading	FirstSolarPVNoPanels	FirstSolarPVPeakPowerPerPanel	FirstSolarPVOrientation	FirstSolarPVTilt	FirstSolarPVOvershading	SecondSolarPVNoPanels	SecondSolarPVPeakPowerPerPanel	SecondSolarPVOrientation	SecondSolarPVTilt	SecondSolarPVOvershading	ThirdSolarPVNoPanels	ThirdSolarPVPeakPowerPerPanel	ThirdSolarPVOrientation	ThirdSolarPVTilt	ThirdSolarPVOvershading	FourthSolarPVNoPanels	FourthSolarPVPeakPowerPerPanel	FourthSolarPVOrientation	FourthSolarPVTilt	FourthSolarPVOvershading	FifthSolarPVNoPanels	FifthSolarPVPeakPowerPerPanel	FifthSolarPVOrientation	FifthSolarPVTilt	FifthSolarPVOvershading	IsSolarPVBatteryPresent	SolarBatteryCapacity	SolarPVEnergyOutput	WindTurbineEnergyOutput	FirstWindTurbineRotorDiameter	FirstWindTurbineHubHeight	FirstWindTurbineTerrainType	SecondWindTurbineRotorDiameter	SecondWindTurbineHubHeight	SecondWindTurbineTerrainType	ThirdWindTurbineRotorDiameter	ThirdWindTurbineHubHeight	ThirdWindTurbineTerrainType	IsPropertyExemptFromZeb	OverrideIsFossilFuelUsedOnSite	IsSystemApplicable	GlobalWarmingPotentialValue	HeatLossIndicator	SHMainPrimaryEnergy	SHSecPrimaryEnergy	WHMainPrimaryEnergy	WHSecPrimaryEnergy	PumpsFansPrimaryEnergy	LightingPrimaryEnergy	CoolingPrimaryEnergy	CHPInputPrimaryEnergy	CHPElecOutputPrimaryEnergy	RenewPrimaryEnergy1	RenewPrimaryEnergy2	RenewPrimaryEnergy3	RenewPrimaryEPTot

In [33]:
# Split only at tabs, because one column name has a space inside it
columns = first_line.strip().split('\t')

print('Number of columns:', len(columns))

# Print each column name on its own line
for col in columns:
    print(col)

Number of columns: 252
CountyName
DwellingTypeDescr
Year_of_Construction
TypeofRating
EnergyRating
BerRating
GroundFloorArea(sq m)
UValueWall
UValueRoof
UValueFloor
UValueWindow
UvalueDoor
WallArea
RoofArea
FloorArea
WindowArea
DoorArea
NoStoreys
CO2Rating
MainSpaceHeatingFuel
MainWaterHeatingFuel
HSMainSystemEfficiency
MultiDwellingMPRN
TGDLEdition
MPCDERValue
HSEffAdjFactor
HSSupplHeatFraction
HSSupplSystemEff
WHMainSystemEff
WHEffAdjFactor
SupplSHFuel
SupplWHFuel
SHRenewableResources
WHRenewableResources
NoOfChimneys
NoOfOpenFlues
NoOfFansAndVents
NoOfFluelessGasFires
DraftLobby
VentilationMethod
FanPowerManuDeclaredValue
HeatExchangerEff
StructureType
SuspendedWoodenFloor
PercentageDraughtStripped
NoOfSidesSheltered
PermeabilityTest
PermeabilityTestResult
TempAdjustment
HeatSystemControlCat
HeatSystemResponseCat
NoCentralHeatingPumps
CHBoilerThermostatControlled
NoOilBoilerHeatingPumps
OBBoilerThermostatControlled
OBPumpInsideDwelling
NoGasBoilerHeatingPumps
WarmAirHeatingSystem
UndergroundHeating
GroundFloorUValue
StorageLosses
ManuLossFactorAvail
SolarHotWaterHeating
ElecImmersionInSummer
CombiBoiler
KeepHotFacility
WaterStorageVolume
DeclaredLossFactor
TempFactorUnadj
TempFactorMultiplier
InsulationType
InsulationThickness
PrimaryCircuitLoss
CombiBoilerAddLoss
ElecConsumpKeepHot
ApertureArea
ZeroLossCollectorEff
CollectorHeatLossCoEff
AnnualSolarRadiation
OvershadingFactor
CylinderStat
SolarStorageVolume
VolumeOfPreHeatStore
CombinedCylinder
ElectricityConsumption
SWHPumpSolarPowered
ChargingBasisHeatConsumed
gsdHSSupplHeatFraction
gsdHSSupplSystemEff
DistLossFactor
CHPUnitHeatFraction
CHPSystemType
CHPSystemTypeDescription
GroupHeatingCO2EQEmissionsFactor
GroupHeatingNonRenewablePEF
GroupHeatingRenewablePEF
HeatLossFromDistributionSystemOutsideDwelling
CHPElecEff
CHPHeatEff
CHPFuelType
SupplHSFuelTypeID
gsdSHRenewableResources
gsdWHRenewableResources
SolarHeatFraction
GroundFloorArea
GroundFloorHeight
FirstFloorArea
FirstFloorHeight
SecondFloorArea
SecondFloorHeight
ThirdFloorArea
ThirdFloorHeight
ThermalBridgingFactor
ThermalMassCategory
PredominantRoofTypeArea
PredominantRoofType
LivingAreaPercent
RoomInRoofArea
PurposeOfRating
DateOfAssessment
FirstEnergyTypeId
FirstEnergyType_Description
FirstEnerProdComment
FirstEnerProdDelivered
FirstPartLTotalContribution
FirstEnerProdConvFactor
FirstEnerProdCO2EmissionFactor
FirstEnerConsumedComment
FirstEnerConsumedDelivered
FirstEnerConsumedConvFactor
FirstEnerConsumedCO2EmissionFactor
SecondEnergyTypeId
SecondEnergyType_Description
SecondEnerProdComment
SecondEnerProdDelivered
SecondPartLTotalContribution
SecondEnerProdConvFactor
SecondEnerProdCO2EmissionFactor
SecondEnerConsumedComment
SecondEnerConsumedDelivered
SecondEnerConsumedConvFactor
SecondEnerConsumedCO2EmissionFactor
ThirdEnergyTypeId
ThirdEnergyType_Description
ThirdEnerProdComment
ThirdEnerProdDelivered
ThirdPartLTotalContribution
ThirdEnerProdConvFactor
ThirdEnerProdCO2EmissionFactor
ThirdEnerConsumedComment
ThirdEnerConsumedDelivered
ThirdEnerConsumedConvFactor
ThirdEnerConsumedCO2EmissionFactor
FirstBoilerFuelType
FirstHeatGenPlantEff
FirstPercentageHeat
SecondBoilerFuelType
SecondHeatGenPlantEff
SecondPercentageHeat
ThirdBoilerFuelType
ThirdHeatGenPlantEff
ThirdPercentageHeat
SolarSpaceHeatingSystem
FirstWallType_Description
FirstWallDescription
FirstWallArea
FirstWallUValue
FirstWallIsSemiExposed
FirstWallAgeBandId
FirstWallTypeId
SecondWallType_Description
SecondWallDescription
SecondWallArea
SecondWallUValue
SecondWallIsSemiExposed
SecondWallAgeBandId
SecondWallTypeId
ThirdWallType_Description
ThirdWallDescription
ThirdWallArea
ThirdWallUValue
ThirdWallIsSemiExposed
ThirdWallAgeBandId
ThirdWallTypeId
SA_Code
prob_smarea_error_0corr
prob_smarea_error_100corr
RER
RenewEPnren
RenewEPren
CPC
EPC
CapacityToWorkAtLowTemperatureLevels
SolarWaterHeatingOrientation
SolarWaterHeatingTiltInDegreesFromHorizontal
SolarWaterHeatingOvershading
FirstSolarPVNoPanels
FirstSolarPVPeakPowerPerPanel
FirstSolarPVOrientation
FirstSolarPVTilt
FirstSolarPVOvershading
SecondSolarPVNoPanels
SecondSolarPVPeakPowerPerPanel
SecondSolarPVOrientation
SecondSolarPVTilt
SecondSolarPVOvershading
ThirdSolarPVNoPanels
ThirdSolarPVPeakPowerPerPanel
ThirdSolarPVOrientation
ThirdSolarPVTilt
ThirdSolarPVOvershading
FourthSolarPVNoPanels
FourthSolarPVPeakPowerPerPanel
FourthSolarPVOrientation
FourthSolarPVTilt
FourthSolarPVOvershading
FifthSolarPVNoPanels
FifthSolarPVPeakPowerPerPanel
FifthSolarPVOrientation
FifthSolarPVTilt
FifthSolarPVOvershading
IsSolarPVBatteryPresent
SolarBatteryCapacity
SolarPVEnergyOutput
WindTurbineEnergyOutput
FirstWindTurbineRotorDiameter
FirstWindTurbineHubHeight
FirstWindTurbineTerrainType
SecondWindTurbineRotorDiameter
SecondWindTurbineHubHeight
SecondWindTurbineTerrainType
ThirdWindTurbineRotorDiameter
ThirdWindTurbineHubHeight
ThirdWindTurbineTerrainType
IsPropertyExemptFromZeb
OverrideIsFossilFuelUsedOnSite
IsSystemApplicable
GlobalWarmingPotentialValue
HeatLossIndicator
SHMainPrimaryEnergy
SHSecPrimaryEnergy
WHMainPrimaryEnergy
WHSecPrimaryEnergy
PumpsFansPrimaryEnergy
LightingPrimaryEnergy
CoolingPrimaryEnergy
CHPInputPrimaryEnergy
CHPElecOutputPrimaryEnergy
RenewPrimaryEnergy1
RenewPrimaryEnergy2
RenewPrimaryEnergy3
RenewPrimaryEPTot

In [34]:
# Read only the first 1000 rows to look at the data (the full file is 1.5 GB)
sample = pd.read_csv(file_path, sep='\t', encoding='latin-1', nrows=1000, low_memory=False)

print(sample.shape)   # (rows, columns)
sample.head()         # show the first 5 rows

# sep='\t' tells pandas the columns are separated by tabs.
# nrows=1000 reads only 1,000 rows, so it loads in seconds.
# low_memory=False stops a warning about mixed data types.

(1000, 252)

,CountyName,DwellingTypeDescr,Year_of_Construction,TypeofRating,EnergyRating,BerRating,GroundFloorArea(sq m),UValueWall,UValueRoof,UValueFloor,UValueWindow,UvalueDoor,WallArea,RoofArea,FloorArea,WindowArea,DoorArea,NoStoreys,CO2Rating,MainSpaceHeatingFuel,MainWaterHeatingFuel,HSMainSystemEfficiency,MultiDwellingMPRN,TGDLEdition,MPCDERValue,HSEffAdjFactor,HSSupplHeatFraction,HSSupplSystemEff,WHMainSystemEff,WHEffAdjFactor,SupplSHFuel,SupplWHFuel,SHRenewableResources,WHRenewableResources,NoOfChimneys,NoOfOpenFlues,NoOfFansAndVents,NoOfFluelessGasFires,DraftLobby,VentilationMethod,FanPowerManuDeclaredValue,HeatExchangerEff,StructureType,SuspendedWoodenFloor,PercentageDraughtStripped,NoOfSidesSheltered,PermeabilityTest,PermeabilityTestResult,TempAdjustment,HeatSystemControlCat,HeatSystemResponseCat,NoCentralHeatingPumps,CHBoilerThermostatControlled,NoOilBoilerHeatingPumps,OBBoilerThermostatControlled,OBPumpInsideDwelling,NoGasBoilerHeatingPumps,WarmAirHeatingSystem,UndergroundHeating,GroundFloorUValue,StorageLosses,ManuLossFactorAvail,SolarHotWaterHeating,ElecImmersionInSummer,CombiBoiler,KeepHotFacility,WaterStorageVolume,DeclaredLossFactor,TempFactorUnadj,TempFactorMultiplier,InsulationType,InsulationThickness,PrimaryCircuitLoss,CombiBoilerAddLoss,ElecConsumpKeepHot,ApertureArea,ZeroLossCollectorEff,CollectorHeatLossCoEff,AnnualSolarRadiation,OvershadingFactor,CylinderStat,SolarStorageVolume,VolumeOfPreHeatStore,CombinedCylinder,ElectricityConsumption,SWHPumpSolarPowered,ChargingBasisHeatConsumed,gsdHSSupplHeatFraction,gsdHSSupplSystemEff,DistLossFactor,CHPUnitHeatFraction,CHPSystemType,CHPSystemTypeDescription,GroupHeatingCO2EQEmissionsFactor,GroupHeatingNonRenewablePEF,GroupHeatingRenewablePEF,HeatLossFromDistributionSystemOutsideDwelling,CHPElecEff,CHPHeatEff,CHPFuelType,SupplHSFuelTypeID,gsdSHRenewableResources,gsdWHRenewableResources,SolarHeatFraction,GroundFloorArea,GroundFloorHeight,FirstFloorArea,FirstFloorHeight,SecondFloorArea,SecondFloorHeight,ThirdFloorArea,ThirdFloorHeight,ThermalBridgingFactor,ThermalMassCategory,PredominantRoofTypeArea,PredominantRoofType,LivingAreaPercent,RoomInRoofArea,PurposeOfRating,DateOfAssessment,FirstEnergyTypeId,FirstEnergyType_Description,FirstEnerProdComment,FirstEnerProdDelivered,FirstPartLTotalContribution,FirstEnerProdConvFactor,FirstEnerProdCO2EmissionFactor,FirstEnerConsumedComment,FirstEnerConsumedDelivered,FirstEnerConsumedConvFactor,FirstEnerConsumedCO2EmissionFactor,SecondEnergyTypeId,SecondEnergyType_Description,SecondEnerProdComment,SecondEnerProdDelivered,SecondPartLTotalContribution,SecondEnerProdConvFactor,SecondEnerProdCO2EmissionFactor,SecondEnerConsumedComment,SecondEnerConsumedDelivered,SecondEnerConsumedConvFactor,SecondEnerConsumedCO2EmissionFactor,ThirdEnergyTypeId,ThirdEnergyType_Description,ThirdEnerProdComment,ThirdEnerProdDelivered,ThirdPartLTotalContribution,ThirdEnerProdConvFactor,ThirdEnerProdCO2EmissionFactor,ThirdEnerConsumedComment,ThirdEnerConsumedDelivered,ThirdEnerConsumedConvFactor,ThirdEnerConsumedCO2EmissionFactor,FirstBoilerFuelType,FirstHeatGenPlantEff,FirstPercentageHeat,SecondBoilerFuelType,SecondHeatGenPlantEff,SecondPercentageHeat,ThirdBoilerFuelType,ThirdHeatGenPlantEff,ThirdPercentageHeat,SolarSpaceHeatingSystem,FirstWallType_Description,FirstWallDescription,FirstWallArea,FirstWallUValue,FirstWallIsSemiExposed,FirstWallAgeBandId,FirstWallTypeId,SecondWallType_Description,SecondWallDescription,SecondWallArea,SecondWallUValue,SecondWallIsSemiExposed,SecondWallAgeBandId,SecondWallTypeId,ThirdWallType_Description,ThirdWallDescription,ThirdWallArea,ThirdWallUValue,ThirdWallIsSemiExposed,ThirdWallAgeBandId,ThirdWallTypeId,SA_Code,prob_smarea_error_0corr,prob_smarea_error_100corr,RER,RenewEPnren,RenewEPren,CPC,EPC,CapacityToWorkAtLowTemperatureLevels,SolarWaterHeatingOrientation,SolarWaterHeatingTiltInDegreesFromHorizontal,SolarWaterHeatingOvershading,FirstSolarPVNoPanels,FirstSolarPVPeakPowerPerPanel,FirstSolarPVOrientation,FirstSolarPVTilt,FirstSolarPVOvershading,SecondSolarPVNoPanels,SecondSolarPVPeakPowerPerPanel,SecondSolarPVOrientation,SecondSolarPVTilt,SecondSolarPVOvershading,ThirdSolarPVNoPanels,ThirdSolarPVPeakPowerPerPanel,ThirdSolarPVOrientation,ThirdSolarPVTilt,ThirdSolarPVOvershading,FourthSolarPVNoPanels,FourthSolarPVPeakPowerPerPanel,FourthSolarPVOrientation,FourthSolarPVTilt,FourthSolarPVOvershading,FifthSolarPVNoPanels,FifthSolarPVPeakPowerPerPanel,FifthSolarPVOrientation,FifthSolarPVTilt,FifthSolarPVOvershading,IsSolarPVBatteryPresent,SolarBatteryCapacity,SolarPVEnergyOutput,WindTurbineEnergyOutput,FirstWindTurbineRotorDiameter,FirstWindTurbineHubHeight,FirstWindTurbineTerrainType,SecondWindTurbineRotorDiameter,SecondWindTurbineHubHeight,SecondWindTurbineTerrainType,ThirdWindTurbineRotorDiameter,ThirdWindTurbineHubHeight,ThirdWindTurbineTerrainType,IsPropertyExemptFromZeb,OverrideIsFossilFuelUsedOnSite,IsSystemApplicable,GlobalWarmingPotentialValue,HeatLossIndicator,SHMainPrimaryEnergy,SHSecPrimaryEnergy,WHMainPrimaryEnergy,WHSecPrimaryEnergy,PumpsFansPrimaryEnergy,LightingPrimaryEnergy,CoolingPrimaryEnergy,CHPInputPrimaryEnergy,CHPElecOutputPrimaryEnergy,RenewPrimaryEnergy1,RenewPrimaryEnergy2,RenewPrimaryEnergy3,RenewPrimaryEPTot
0,Co. Tipperary,Semi-detached house,2001,Existing,D1,247.21,100.04,0.38,0.13,0.44,2.60,3.00,121.45,51.84,51.84,16.19,5.55,2,63.40,Heating Oil,Heating Oil,85.3,NO,0,56.23,0.95,0.1,30.0,85.3,0.95,15.0,1.0,2.0,2.0,1,0,8,0,NO,Natural vent.,0.0,0,Masonry,No,100,2,NO,0.0,0.6,1,1,1,NO,1,NO,NO,0,NO,NO,0.0,YES,NO,NO,NO,None,keep-hot facility fuelled by g,96.0,0.0,0.6,1.30,Loose Jacket,0.0,Boiler with uninsulated primar,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NO,NaN,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.84,2.50,48.20,2.65,0.0,0.0,0.0,0.0,0.15,Medium,51.84,Pitch Roof-Insul.on Ceiling,16.57340,0.00,Unknown,Oct 8 2011 12:00AM,1.0,Renewable Thermal,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,1.0,Renewable Thermal,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,1.0,Renewable Thermal,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300mm Filled Cavity,NaN,115.80,0.29,No,9.0,5,Other,single block,5.65,2.230,Yes,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Co. Carlow,Detached house,1900,Existing,E2,357.95,90.72,1.70,0.84,0.94,2.80,3.02,122.49,30.15,60.57,8.79,3.58,2,88.26,Heating Oil,Heating Oil,70.0,NO,0,44.34,0.95,0.0,0.0,70.0,0.95,1.0,1.0,2.0,2.0,0,0,1,0,NO,Natural vent.,0.0,0,Masonry,No,100,2,NO,0.0,0.0,3,1,1,NO,0,NO,NO,0,NO,NO,0.0,YES,NO,NO,NO,None,keep-hot facility fuelled by g,110.0,0.0,0.6,1.17,Loose Jacket,80.0,Boiler with uninsulated primar,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NO,NaN,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.57,2.47,30.15,2.26,0.0,0.0,0.0,0.0,0.15,Medium,20.29,Pitch Roof-Insul.on Ceiling,22.46470,0.00,Unknown,Oct 31 2011 12:00AM,1.0,Renewable Thermal,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,1.0,Renewable Thermal,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,1.0,Renewable Thermal,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stone,Orig,90.05,2.10,No,2.0,1,300mm Filled Cavity,NaN,32.44,0.600,No,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Dublin 6,Semi-detached house,1923,Existing,C3,219.51,163.02,2.10,2.30,0.56,2.71,3.00,82.72,45.11,75.07,21.93,4.55,3,47.52,Mains Gas,Mains Gas,90.5,NO,0,24.79,1.00,0.1,35.0,90.5,1.00,15.0,1.0,2.0,2.0,1,0,3,0,NO,Natural vent.,0.0,0,Masonry,Yes (Unsealed),100,2,NO,0.0,0.0,3,1,1,YES,0,NO,NO,1,NO,NO,0.0,YES,NO,NO,NO,None,keep-hot facility fuelled by g,119.0,0.0,1.0,1.00,Factory Insulated,30.0,Boiler with insulated primary,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NO,NaN,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.07,2.64,75.07,2.47,0.0,0.0,0.0,0.0,0.15,Medium,45.11,Room in Roof-Insul.on side,9.36081,12.88,Unknown,Oct 22 2011 12:00AM,1.0,Renewable Thermal,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,1.0,Renewable Thermal,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,1.0,Renewable Thermal,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,225mm Solid brick,Exposed external walls,82.72,2.10,No,2.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Co. Tipperary,Detached house,2003,Existing,D2,264.87,107.98,0.29,0.13,0.41,3.10,4.56,83.18,107.98,107.98,17.45,8.93,1,68.12,Heating Oil,Heating Oil,85.0,NO,0,57.84,0.95,0.1,30.0,85.0,0.95,15.0,1.0,2.0,2.0,1,0,3,0,NO,Natural vent.,0.0,0,Masonry,No,100,1,NO,0.0,0.6,1,1,1,NO,1,NO,NO,0,NO,NO,0.0,YES,NO,NO,NO,None,keep-hot facility fuelled by g,88.0,0.0,0.6,1.30,Loose Jacket,0.0,Boiler with uninsulated primar,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NO,NaN,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.98,2.48,0.00,0.00,0.0,0.0,0.0,0.0,0.15,Medium,92.33,Pitch Roof-Insul.on Ceiling,11.24280,0.00,Unknown,Oct 31 2011 12:00AM,1.0,Renewable Thermal,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,1.0,Renewable Thermal,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,1.0,Renewable Thermal,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300mm Cavity,rear elevation same,27.86,0.29,No,9.0,4,300mm Cavity,front elevation cavity wall 50,21.75,0.290,No,9.0,4.0,300mm Cavity,right elevation same,18.10,0.29,No,9.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Co. Clare,Detached house,1987,Existing,C3,222.66,241.56,0.32,0.28,0.59,2.80,3.00,136.27,247.20,152.27,33.74,1.85,2,56.04,Heating Oil,Heating Oil,70.0,NO,0,46.20,0.95,0.1,50.0,70.0,0.95,6.0,28.0,2.0,2.0,1,0,1,0,NO,Natural vent.,0.0,0,Masonry,No,100,1,NO,0.0,0.6,1,1,1,NO,1,NO,NO,0,NO,NO,0.0,YES,NO,NO,YES,None,keep-hot facility fuelled by g,203.0,0.0,0.6,1.30,Loose Jacket,25.0,Boiler with uninsulated primar,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NO,NaN,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,138.56,2.61,103.00,2.37,0.0,0.0,0.0,0.0,0.15,Medium-low,70.91,Pitch Roof-Insul.on Ceiling,8.71419,0.00,Unknown,Oct 11 2011 12:00AM,1.0,Renewable Thermal,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,1.0,Renewable Thermal,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,1.0,Renewable Thermal,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300mm Cavity,Main Dwelling,111.65,0.32,No,7.0,4,300mm Cavity,Adjacent to Garage,21.19,0.296,Yes,7.0,4.0,Timber Frame,Dorner Window Wing Walls,3.43,0.60,No,7.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
pieces = []

# Read the file 100,000 rows at a time
reader = pd.read_csv(file_path, sep='\t', encoding='latin-1', low_memory=False,
                     on_bad_lines='warn', chunksize=100000)

for chunk in reader:
    # Turn the date column into real dates
    chunk['DateOfAssessment'] = pd.to_datetime(chunk['DateOfAssessment'], dayfirst=True, errors='coerce')

    # Keep only assessments from 2021 to 2025
    chunk = chunk[(chunk['DateOfAssessment'] >= '2021-01-01') & (chunk['DateOfAssessment'] < '2026-01-01')]

    pieces.append(chunk)
    print('Rows kept so far:', sum(len(p) for p in pieces))

# Join all the pieces into one table
ber = pd.concat(pieces, ignore_index=True)
print(ber.shape)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\2438266631.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  chunk['DateOfAssessment'] = pd.to_datetime(chunk['DateOfAssessment'], dayfirst=True, errors='coerce')

Rows kept so far: 0

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\2438266631.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  chunk['DateOfAssessment'] = pd.to_datetime(chunk['DateOfAssessment'], dayfirst=True, errors='coerce')

Rows kept so far: 0

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\2438266631.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  chunk['DateOfAssessment'] = pd.to_datetime(chunk['DateOfAssessment'], dayfirst=True, errors='coerce')

Rows kept so far: 0

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\2438266631.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  chunk['DateOfAssessment'] = pd.to_datetime(chunk['DateOfAssessment'], dayfirst=True, errors='coerce')

Rows kept so far: 0

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\2438266631.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  chunk['DateOfAssessment'] = pd.to_datetime(chunk['DateOfAssessment'], dayfirst=True, errors='coerce')

Rows kept so far: 0

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\2438266631.py:7: ParserWarning: Skipping line 553867: expected 252 fields, saw 259

  for chunk in reader:
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\2438266631.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  chunk['DateOfAssessment'] = pd.to_datetime(chunk['DateOfAssessment'], dayfirst=True, errors='coerce')

Rows kept so far: 0

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\2438266631.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  chunk['DateOfAssessment'] = pd.to_datetime(chunk['DateOfAssessment'], dayfirst=True, errors='coerce')

Rows kept so far: 8375

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\2438266631.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  chunk['DateOfAssessment'] = pd.to_datetime(chunk['DateOfAssessment'], dayfirst=True, errors='coerce')

Rows kept so far: 107027

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\2438266631.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  chunk['DateOfAssessment'] = pd.to_datetime(chunk['DateOfAssessment'], dayfirst=True, errors='coerce')

Rows kept so far: 206765

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\2438266631.py:7: ParserWarning: Skipping line 974530: expected 252 fields, saw 294

  for chunk in reader:
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\2438266631.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  chunk['DateOfAssessment'] = pd.to_datetime(chunk['DateOfAssessment'], dayfirst=True, errors='coerce')

Rows kept so far: 306714

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\2438266631.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  chunk['DateOfAssessment'] = pd.to_datetime(chunk['DateOfAssessment'], dayfirst=True, errors='coerce')

Rows kept so far: 406696

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\2438266631.py:7: ParserWarning: Skipping line 1140091: expected 252 fields, saw 263

  for chunk in reader:
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\2438266631.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  chunk['DateOfAssessment'] = pd.to_datetime(chunk['DateOfAssessment'], dayfirst=True, errors='coerce')

Rows kept so far: 506673

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\2438266631.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  chunk['DateOfAssessment'] = pd.to_datetime(chunk['DateOfAssessment'], dayfirst=True, errors='coerce')

Rows kept so far: 563197

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\2438266631.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  chunk['DateOfAssessment'] = pd.to_datetime(chunk['DateOfAssessment'], dayfirst=True, errors='coerce')

Rows kept so far: 564396

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\2438266631.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  chunk['DateOfAssessment'] = pd.to_datetime(chunk['DateOfAssessment'], dayfirst=True, errors='coerce')

Rows kept so far: 569058
(569058, 252)

In [36]:
ber.head()

,CountyName,DwellingTypeDescr,Year_of_Construction,TypeofRating,EnergyRating,BerRating,GroundFloorArea(sq m),UValueWall,UValueRoof,UValueFloor,UValueWindow,UvalueDoor,WallArea,RoofArea,FloorArea,WindowArea,DoorArea,NoStoreys,CO2Rating,MainSpaceHeatingFuel,MainWaterHeatingFuel,HSMainSystemEfficiency,MultiDwellingMPRN,TGDLEdition,MPCDERValue,HSEffAdjFactor,HSSupplHeatFraction,HSSupplSystemEff,WHMainSystemEff,WHEffAdjFactor,SupplSHFuel,SupplWHFuel,SHRenewableResources,WHRenewableResources,NoOfChimneys,NoOfOpenFlues,NoOfFansAndVents,NoOfFluelessGasFires,DraftLobby,VentilationMethod,FanPowerManuDeclaredValue,HeatExchangerEff,StructureType,SuspendedWoodenFloor,PercentageDraughtStripped,NoOfSidesSheltered,PermeabilityTest,PermeabilityTestResult,TempAdjustment,HeatSystemControlCat,HeatSystemResponseCat,NoCentralHeatingPumps,CHBoilerThermostatControlled,NoOilBoilerHeatingPumps,OBBoilerThermostatControlled,OBPumpInsideDwelling,NoGasBoilerHeatingPumps,WarmAirHeatingSystem,UndergroundHeating,GroundFloorUValue,StorageLosses,ManuLossFactorAvail,SolarHotWaterHeating,ElecImmersionInSummer,CombiBoiler,KeepHotFacility,WaterStorageVolume,DeclaredLossFactor,TempFactorUnadj,TempFactorMultiplier,InsulationType,InsulationThickness,PrimaryCircuitLoss,CombiBoilerAddLoss,ElecConsumpKeepHot,ApertureArea,ZeroLossCollectorEff,CollectorHeatLossCoEff,AnnualSolarRadiation,OvershadingFactor,CylinderStat,SolarStorageVolume,VolumeOfPreHeatStore,CombinedCylinder,ElectricityConsumption,SWHPumpSolarPowered,ChargingBasisHeatConsumed,gsdHSSupplHeatFraction,gsdHSSupplSystemEff,DistLossFactor,CHPUnitHeatFraction,CHPSystemType,CHPSystemTypeDescription,GroupHeatingCO2EQEmissionsFactor,GroupHeatingNonRenewablePEF,GroupHeatingRenewablePEF,HeatLossFromDistributionSystemOutsideDwelling,CHPElecEff,CHPHeatEff,CHPFuelType,SupplHSFuelTypeID,gsdSHRenewableResources,gsdWHRenewableResources,SolarHeatFraction,GroundFloorArea,GroundFloorHeight,FirstFloorArea,FirstFloorHeight,SecondFloorArea,SecondFloorHeight,ThirdFloorArea,ThirdFloorHeight,ThermalBridgingFactor,ThermalMassCategory,PredominantRoofTypeArea,PredominantRoofType,LivingAreaPercent,RoomInRoofArea,PurposeOfRating,DateOfAssessment,FirstEnergyTypeId,FirstEnergyType_Description,FirstEnerProdComment,FirstEnerProdDelivered,FirstPartLTotalContribution,FirstEnerProdConvFactor,FirstEnerProdCO2EmissionFactor,FirstEnerConsumedComment,FirstEnerConsumedDelivered,FirstEnerConsumedConvFactor,FirstEnerConsumedCO2EmissionFactor,SecondEnergyTypeId,SecondEnergyType_Description,SecondEnerProdComment,SecondEnerProdDelivered,SecondPartLTotalContribution,SecondEnerProdConvFactor,SecondEnerProdCO2EmissionFactor,SecondEnerConsumedComment,SecondEnerConsumedDelivered,SecondEnerConsumedConvFactor,SecondEnerConsumedCO2EmissionFactor,ThirdEnergyTypeId,ThirdEnergyType_Description,ThirdEnerProdComment,ThirdEnerProdDelivered,ThirdPartLTotalContribution,ThirdEnerProdConvFactor,ThirdEnerProdCO2EmissionFactor,ThirdEnerConsumedComment,ThirdEnerConsumedDelivered,ThirdEnerConsumedConvFactor,ThirdEnerConsumedCO2EmissionFactor,FirstBoilerFuelType,FirstHeatGenPlantEff,FirstPercentageHeat,SecondBoilerFuelType,SecondHeatGenPlantEff,SecondPercentageHeat,ThirdBoilerFuelType,ThirdHeatGenPlantEff,ThirdPercentageHeat,SolarSpaceHeatingSystem,FirstWallType_Description,FirstWallDescription,FirstWallArea,FirstWallUValue,FirstWallIsSemiExposed,FirstWallAgeBandId,FirstWallTypeId,SecondWallType_Description,SecondWallDescription,SecondWallArea,SecondWallUValue,SecondWallIsSemiExposed,SecondWallAgeBandId,SecondWallTypeId,ThirdWallType_Description,ThirdWallDescription,ThirdWallArea,ThirdWallUValue,ThirdWallIsSemiExposed,ThirdWallAgeBandId,ThirdWallTypeId,SA_Code,prob_smarea_error_0corr,prob_smarea_error_100corr,RER,RenewEPnren,RenewEPren,CPC,EPC,CapacityToWorkAtLowTemperatureLevels,SolarWaterHeatingOrientation,SolarWaterHeatingTiltInDegreesFromHorizontal,SolarWaterHeatingOvershading,FirstSolarPVNoPanels,FirstSolarPVPeakPowerPerPanel,FirstSolarPVOrientation,FirstSolarPVTilt,FirstSolarPVOvershading,SecondSolarPVNoPanels,SecondSolarPVPeakPowerPerPanel,SecondSolarPVOrientation,SecondSolarPVTilt,SecondSolarPVOvershading,ThirdSolarPVNoPanels,ThirdSolarPVPeakPowerPerPanel,ThirdSolarPVOrientation,ThirdSolarPVTilt,ThirdSolarPVOvershading,FourthSolarPVNoPanels,FourthSolarPVPeakPowerPerPanel,FourthSolarPVOrientation,FourthSolarPVTilt,FourthSolarPVOvershading,FifthSolarPVNoPanels,FifthSolarPVPeakPowerPerPanel,FifthSolarPVOrientation,FifthSolarPVTilt,FifthSolarPVOvershading,IsSolarPVBatteryPresent,SolarBatteryCapacity,SolarPVEnergyOutput,WindTurbineEnergyOutput,FirstWindTurbineRotorDiameter,FirstWindTurbineHubHeight,FirstWindTurbineTerrainType,SecondWindTurbineRotorDiameter,SecondWindTurbineHubHeight,SecondWindTurbineTerrainType,ThirdWindTurbineRotorDiameter,ThirdWindTurbineHubHeight,ThirdWindTurbineTerrainType,IsPropertyExemptFromZeb,OverrideIsFossilFuelUsedOnSite,IsSystemApplicable,GlobalWarmingPotentialValue,HeatLossIndicator,SHMainPrimaryEnergy,SHSecPrimaryEnergy,WHMainPrimaryEnergy,WHSecPrimaryEnergy,PumpsFansPrimaryEnergy,LightingPrimaryEnergy,CoolingPrimaryEnergy,CHPInputPrimaryEnergy,CHPElecOutputPrimaryEnergy,RenewPrimaryEnergy1,RenewPrimaryEnergy2,RenewPrimaryEnergy3,RenewPrimaryEPTot
0,Co. Kildare,Detached house,2000,Existing,E1,339.72,25.65,0.55,0.36,0.52,2.80,3.00,50.75,25.65,25.65,3.47,1.85,1,79.15,Heating Oil,Heating Oil,85.60,YES,0,65.66,0.95,0.0,0.0,85.60,0.95,1.0,28.0,1.0,1.0,0.0,0.0,1.0,0.0,YES,Natural vent.,0.00,0.0,Masonry,No,100.0,2.0,NO,0.0,0.0,1,1,1,YES,1,NO,NO,0,NO,NO,0.0,YES,NO,NO,YES,None,inapplicable,110.0,0.0,0.6,1.3,Factory Insulated,30.0,Boiler with uninsulated primar,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NO,NaN,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.65,2.37,0.0,0.0,0.0,0.0,0.0,0.0,0.15,Medium,25.65,Pitch Roof-Insul.on Rafter,45.61,0.0,Private Letting,2021-01-01,1.0,Renewable Thermal, ,0.00,0.00,0.0,0.000, ,0.0,0.0,0.0,1.0,Renewable Thermal, ,0.0,0.0,0.0,0.0, ,0.0,0.0,0.0,1.0,Renewable Thermal, ,0.0,0.0,0.0,0.0, ,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,50.75,0.55,No,9.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,8275.79,0.0,1.217,1.056,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4324.60,0.00,1932.40,929.89,1348.62,178.41,NaN,0.0,0.0,0.0,0.0,0.0,8275.79
1,Co. Kildare,Detached house,2000,Existing,D2,290.10,40.82,0.55,0.36,0.49,2.80,3.00,59.83,40.82,40.82,8.87,3.70,1,68.41,Heating Oil,Heating Oil,85.60,YES,0,51.77,0.95,0.0,0.0,85.60,0.95,1.0,28.0,1.0,1.0,0.0,0.0,2.0,0.0,YES,Natural vent.,0.00,0.0,Masonry,No,100.0,2.0,NO,0.0,0.0,1,1,1,YES,1,NO,NO,0,NO,NO,0.0,YES,NO,NO,YES,None,inapplicable,110.0,0.0,0.6,1.3,Factory Insulated,30.0,Boiler with uninsulated primar,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NO,NaN,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.82,2.38,0.0,0.0,0.0,0.0,0.0,0.0,0.15,Medium,40.82,Pitch Roof-Insul.on Rafter,42.33,0.0,Private Letting,2021-01-01,1.0,Renewable Thermal, ,0.00,0.00,0.0,0.000, ,0.0,0.0,0.0,1.0,Renewable Thermal, ,0.0,0.0,0.0,0.0, ,0.0,0.0,0.0,1.0,Renewable Thermal, ,0.0,0.0,0.0,0.0, ,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,59.83,0.55,No,9.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,11375.40,0.0,1.314,1.136,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7108.39,0.00,2057.21,989.85,1453.54,232.77,NaN,0.0,0.0,0.0,0.0,0.0,11375.40
2,Co. Kildare,Detached house,2000,Existing,D2,290.33,40.82,0.55,0.36,0.49,2.80,3.00,59.83,40.82,40.82,8.87,3.70,1,68.47,Heating Oil,Heating Oil,85.60,YES,0,51.81,0.95,0.0,0.0,85.60,0.95,1.0,28.0,1.0,1.0,0.0,0.0,2.0,0.0,YES,Natural vent.,0.00,0.0,Masonry,No,100.0,2.0,NO,0.0,0.0,1,1,1,YES,1,NO,NO,0,NO,NO,0.0,YES,NO,NO,YES,None,inapplicable,110.0,0.0,0.6,1.3,Factory Insulated,30.0,Boiler with uninsulated primar,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NO,NaN,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.82,2.38,0.0,0.0,0.0,0.0,0.0,0.0,0.15,Medium,40.82,Pitch Roof-Insul.on Rafter,43.04,0.0,Private Letting,2021-01-01,1.0,Renewable Thermal, ,0.00,0.00,0.0,0.000, ,0.0,0.0,0.0,1.0,Renewable Thermal, ,0.0,0.0,0.0,0.0, ,0.0,0.0,0.0,1.0,Renewable Thermal, ,0.0,0.0,0.0,0.0, ,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,59.83,0.55,No,9.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,11385.00,0.0,1.314,1.136,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7118.03,0.00,2057.21,989.85,1453.54,232.77,NaN,0.0,0.0,0.0,0.0,0.0,11385.00
3,Co. Cork,Semi-detached house,1930,Existing,A1,24.52,147.70,0.24,0.18,0.11,1.25,1.40,114.06,99.66,105.30,30.56,1.85,2,5.75,Electricity,Electricity,464.67,NO,0,47.31,1.00,0.1,77.0,257.63,1.00,8.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,NO,Bal.whole mech.vent heat recvr,0.63,90.0,Masonry,No,100.0,2.0,NO,0.0,0.0,3,3,1,YES,0,NO,NO,0,NO,NO,0.0,YES,YES,NO,NO,None,inapplicable,230.0,1.4,0.6,0.9,None,0.0,Boiler with uninsulated primar,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NO,NaN,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.30,2.46,42.4,2.7,0.0,0.0,0.0,0.0,0.15,Medium,42.40,Pitch Roof-Insul.on Ceiling,18.35,0.0,Major Renovation,2021-01-01,2.0,Renewable Electrical,PV,2169.06,2169.06,2.08,0.409, ,0.0,0.0,0.0,1.0,Renewable Thermal, ,0.0,0.0,0.0,0.0, ,0.0,0.0,0.0,1.0,Renewable Thermal, ,0.0,0.0,0.0,0.0, ,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other,NEW WALLS 150MM PUMPED CAVITY,63.65,0.21,No,3.0,9.0,Other,WALLS WITH 100MM EXTERNAL WALL,50.41,0.271,No,3.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.764,3532.67,11435.6,0.184,0.162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2169.06,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2717.66,1059.47,2849.31,0.00,867.54,638.62,NaN,0.0,0.0,0.0,0.0,0.0,14968.30
4,Co. Laois,Detached house,1850,Existing,G,1200.95,71.89,2.10,2.30,0.94,4.48,1.71,99.73,71.89,71.89,6.40,1.75,1,390.47,Solid Multi-Fuel,Solid Multi-Fuel,45.00,NO,0,121.35,1.00,0.1,30.0,45.00,1.00,15.0,28.0,1.0,1.0,2.0,1.0,0.0,0.0,YES,Natural vent.,0.00,0.0,Masonry,No,13.0,1.0,NO,0.0,0.6,1,2,1,NO,0,NO,NO,0,NO,NO,0.0,YES,NO,NO,YES,None,inapplicable,95.0,0.0,0.6,1.3,None,0.0,Boiler with uninsulated primar,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NO,NaN,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71.89,2.86,0.0,0.0,0.0,0.0,0.0,0.0,0.15,High,71.89,Pitch Roof-Insul.on Ceiling,25.59,0.0,Sale,2021-01-02,1.0,Renewable Thermal, ,0.00,0.00,0.0,0.000, ,0.0,0.0,0.0,1.0,Renewable Thermal, ,0.0,0.0,0.0,0.0, ,0.0,0.0,0.0,1.0,Renewable Thermal, ,0.0,0.0,0.0,0.0, ,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stone,NaN,99.73,2.10,No,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,84803.70,0.0,8.758,5.521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60484.50,10101.50,9330.84,3252.07,1875.79,1291.29,NaN,0.0,0.0,0.0,0.0,0.0,84803.70

In [37]:
pd.set_option('display.max_rows', None)
ber.isnull().sum()

CountyName                                            0
DwellingTypeDescr                                     0
Year_of_Construction                                  0
TypeofRating                                          0
EnergyRating                                          0
BerRating                                             0
GroundFloorArea(sq m)                                 0
UValueWall                                            0
UValueRoof                                            0
UValueFloor                                           0
UValueWindow                                          0
UvalueDoor                                            0
WallArea                                              0
RoofArea                                              0
FloorArea                                             0
WindowArea                                            0
DoorArea                                              0
NoStoreys                                             0
CO2Rating                                             0
MainSpaceHeatingFuel                              12335
MainWaterHeatingFuel                              12335
HSMainSystemEfficiency                            12335
MultiDwellingMPRN                                     0
TGDLEdition                                           0
MPCDERValue                                           0
HSEffAdjFactor                                    12335
HSSupplHeatFraction                               12335
HSSupplSystemEff                                  12335
WHMainSystemEff                                   12335
WHEffAdjFactor                                    12335
SupplSHFuel                                       12335
SupplWHFuel                                       12335
SHRenewableResources                              12335
WHRenewableResources                              12335
NoOfChimneys                                      23095
NoOfOpenFlues                                     23095
NoOfFansAndVents                                  23095
NoOfFluelessGasFires                              23095
DraftLobby                                        23095
VentilationMethod                                 23095
FanPowerManuDeclaredValue                         23095
HeatExchangerEff                                  23095
StructureType                                     23095
SuspendedWoodenFloor                              23095
PercentageDraughtStripped                         23095
NoOfSidesSheltered                                23095
PermeabilityTest                                  23095
PermeabilityTestResult                            23095
TempAdjustment                                        0
HeatSystemControlCat                                  0
HeatSystemResponseCat                                 0
NoCentralHeatingPumps                                 0
CHBoilerThermostatControlled                          0
NoOilBoilerHeatingPumps                               0
OBBoilerThermostatControlled                          0
OBPumpInsideDwelling                                  0
NoGasBoilerHeatingPumps                               0
WarmAirHeatingSystem                                  0
UndergroundHeating                                    0
GroundFloorUValue                                     0
StorageLosses                                         0
ManuLossFactorAvail                                   0
SolarHotWaterHeating                                  0
ElecImmersionInSummer                                 0
CombiBoiler                                           0
KeepHotFacility                                       0
WaterStorageVolume                                    0
DeclaredLossFactor                                    0
TempFactorUnadj                                       0
TempFactorMultiplier                                  0
InsulationType                                        0
InsulationThickness                                   0
PrimaryCircuitLoss                                    0
CombiBoilerAddLoss                                    0
ElecConsumpKeepHot                                    0
ApertureArea                                     550708
ZeroLossCollectorEff                             550708
CollectorHeatLossCoEff                           550708
AnnualSolarRadiation                             550717
OvershadingFactor                                550708
CylinderStat                                          0
SolarStorageVolume                               550708
VolumeOfPreHeatStore                             550708
CombinedCylinder                                      0
ElectricityConsumption                           550708
SWHPumpSolarPowered                                   0
ChargingBasisHeatConsumed                             0
gsdHSSupplHeatFraction                           556723
gsdHSSupplSystemEff                              556723
DistLossFactor                                   556723
CHPUnitHeatFraction                              556723
CHPSystemType                                    556723
CHPSystemTypeDescription                         561967
GroupHeatingCO2EQEmissionsFactor                 569058
GroupHeatingNonRenewablePEF                      556723
GroupHeatingRenewablePEF                         556723
HeatLossFromDistributionSystemOutsideDwelling    568105
CHPElecEff                                       556723
CHPHeatEff                                       556723
CHPFuelType                                      556723
SupplHSFuelTypeID                                556723
gsdSHRenewableResources                          569058
gsdWHRenewableResources                          569058
SolarHeatFraction                                556723
GroundFloorArea                                       0
GroundFloorHeight                                     0
FirstFloorArea                                        0
FirstFloorHeight                                      0
SecondFloorArea                                       0
SecondFloorHeight                                     0
ThirdFloorArea                                        0
ThirdFloorHeight                                      0
ThermalBridgingFactor                                 0
ThermalMassCategory                                   0
PredominantRoofTypeArea                           66673
PredominantRoofType                               66673
LivingAreaPercent                                     0
RoomInRoofArea                                        0
PurposeOfRating                                       0
DateOfAssessment                                      0
FirstEnergyTypeId                                 12337
FirstEnergyType_Description                       12337
FirstEnerProdComment                              12343
FirstEnerProdDelivered                            12337
FirstPartLTotalContribution                       12337
FirstEnerProdConvFactor                           12337
FirstEnerProdCO2EmissionFactor                    12337
FirstEnerConsumedComment                          12337
FirstEnerConsumedDelivered                        12338
FirstEnerConsumedConvFactor                       12338
FirstEnerConsumedCO2EmissionFactor                12338
SecondEnergyTypeId                                12338
SecondEnergyType_Description                      12338
SecondEnerProdComment                             12338
SecondEnerProdDelivered                           12338
SecondPartLTotalContribution                      12338
SecondEnerProdConvFactor                          12338
SecondEnerProdCO2EmissionFactor                   12338
SecondEnerConsumedComment                         12338
SecondEnerConsumedDelivered                       12338
SecondEnerConsumedConvFactor                      12338
SecondEnerConsumedCO2EmissionFactor               12338
ThirdEnergyTypeId                                 12339
ThirdEnergyType_Description                       12339
ThirdEnerProdComment                              12339
ThirdEnerProdDelivered                            12337
ThirdPartLTotalContribution                       12337
ThirdEnerProdConvFactor                           12337
ThirdEnerProdCO2EmissionFactor                    12337
ThirdEnerConsumedComment                          12338
ThirdEnerConsumedDelivered                        12339
ThirdEnerConsumedConvFactor                       12339
ThirdEnerConsumedCO2EmissionFactor                12339
FirstBoilerFuelType                              556723
FirstHeatGenPlantEff                             556723
FirstPercentageHeat                              556723
SecondBoilerFuelType                             556723
SecondHeatGenPlantEff                            556723
SecondPercentageHeat                             556723
ThirdBoilerFuelType                              556725
ThirdHeatGenPlantEff                             556725
ThirdPercentageHeat                              556725
SolarSpaceHeatingSystem                          556723
FirstWallType_Description                             2
FirstWallDescription                             232707
FirstWallArea                                         2
FirstWallUValue                                       2
FirstWallIsSemiExposed                                2
FirstWallAgeBandId                                    9
FirstWallTypeId                                       2
SecondWallType_Description                       289358
SecondWallDescription                            380392
SecondWallArea                                   289358
SecondWallUValue                                 289358
SecondWallIsSemiExposed                          289358
SecondWallAgeBandId                              289362
SecondWallTypeId                                 289358
ThirdWallType_Description                        465602
ThirdWallDescription                             488845
ThirdWallArea                                    465600
ThirdWallUValue                                  465599
ThirdWallIsSemiExposed                           465599
ThirdWallAgeBandId                               465601
ThirdWallTypeId                                  465601
SA_Code                                          569057
prob_smarea_error_0corr                          569058
prob_smarea_error_100corr                        569058
RER                                                   3
RenewEPnren                                           5
RenewEPren                                            5
CPC                                                   3
EPC                                                   3
CapacityToWorkAtLowTemperatureLevels             569058
SolarWaterHeatingOrientation                     569049
SolarWaterHeatingTiltInDegreesFromHorizontal     569049
SolarWaterHeatingOvershading                     569049
FirstSolarPVNoPanels                             568912
FirstSolarPVPeakPowerPerPanel                    568912
FirstSolarPVOrientation                          568912
FirstSolarPVTilt                                 568912
FirstSolarPVOvershading                          568912
SecondSolarPVNoPanels                            569028
SecondSolarPVPeakPowerPerPanel                   569028
SecondSolarPVOrientation                         569028
SecondSolarPVTilt                                569028
SecondSolarPVOvershading                         569028
ThirdSolarPVNoPanels                             569051
ThirdSolarPVPeakPowerPerPanel                    569051
ThirdSolarPVOrientation                          569051
ThirdSolarPVTilt                                 569051
ThirdSolarPVOvershading                          569053
FourthSolarPVNoPanels                            569057
FourthSolarPVPeakPowerPerPanel                   569057
FourthSolarPVOrientation                         569057
FourthSolarPVTilt                                569056
FourthSolarPVOvershading                         569056
FifthSolarPVNoPanels                             569057
FifthSolarPVPeakPowerPerPanel                    569057
FifthSolarPVOrientation                          569058
FifthSolarPVTilt                                 569058
FifthSolarPVOvershading                          569058
IsSolarPVBatteryPresent                               3
SolarBatteryCapacity                                  3
SolarPVEnergyOutput                                   3
WindTurbineEnergyOutput                               3
FirstWindTurbineRotorDiameter                    569058
FirstWindTurbineHubHeight                        569058
FirstWindTurbineTerrainType                      569058
SecondWindTurbineRotorDiameter                   569058
SecondWindTurbineHubHeight                       569058
SecondWindTurbineTerrainType                     569058
ThirdWindTurbineRotorDiameter                    569057
ThirdWindTurbineHubHeight                        569057
ThirdWindTurbineTerrainType                      569057
IsPropertyExemptFromZeb                          568104
OverrideIsFossilFuelUsedOnSite                   568104
IsSystemApplicable                               568104
GlobalWarmingPotentialValue                      568104
HeatLossIndicator                                 95554
SHMainPrimaryEnergy                                   4
SHSecPrimaryEnergy                                    4
WHMainPrimaryEnergy                                   4
WHSecPrimaryEnergy                                    4
PumpsFansPrimaryEnergy                                4
LightingPrimaryEnergy                                 4
CoolingPrimaryEnergy                              95557
CHPInputPrimaryEnergy                                 5
CHPElecOutputPrimaryEnergy                            5
RenewPrimaryEnergy1                                   5
RenewPrimaryEnergy2                                   5
RenewPrimaryEnergy3                                   5
RenewPrimaryEPTot                                     5
dtype: int64

# BER Research Tool (SEAI): Column Dictionary

**Dataset:** 569,058 BER assessments (2021–2025), 252 columns. One row = one BER certificate.

**Tags:**
- **[TARGET]**: what we want to predict
- **[LEAKAGE]**: calculated from the rating itself, so do **NOT** use as a model input
- **(?)**: meaning not 100% confirmed; check SEAI DEAP manual

---

## 1. Location, Time and Purpose
| Column | Meaning |
|---|---|
| CountyName | County of the home ("Co. Kildare"), or Dublin postal district ("Dublin 6") |
| DwellingTypeDescr | Type of home: detached, semi-detached, terraced, apartment, etc. |
| Year_of_Construction | Year the home was built |
| TypeofRating | Existing home, new home (final), or provisional (planned) rating |
| PurposeOfRating | Why the BER was done: sale, private letting, grant, new build, unknown |
| DateOfAssessment | Date the assessor did the BER |
| MultiDwellingMPRN | YES/NO: electricity meter (MPRN) shared by several homes |
| SA_Code | CSO Census Small Area code (very local area) |
| prob_smarea_error_0corr / prob_smarea_error_100corr | Estimated chance the Small Area code is wrong (?) |
| TGDLEdition | Edition of Building Regulations Part L (TGD L) the home was assessed against |

## 2. Rating Results (outputs of the BER calculation)
| Column | Meaning |
|---|---|
| BerRating | **[TARGET]** Energy use in kWh per m² per year (lower = better) |
| EnergyRating | **[TARGET]** BER band A1 (best) to G (worst), made from BerRating |
| CO2Rating | **[LEAKAGE]** CO₂ emissions in kg per m² per year |
| MPCDERValue | **[LEAKAGE]** Part L compliance CO₂/energy reference value (?) |
| EPC | **[LEAKAGE]** Energy Performance Coefficient (Part L check for new homes) |
| CPC | **[LEAKAGE]** Carbon Performance Coefficient (Part L check for new homes) |
| RER | **[LEAKAGE]** Renewable Energy Ratio (share of energy from renewables) |
| RenewEPnren / RenewEPren | **[LEAKAGE]** Non-renewable / renewable primary energy used for RER |
| HeatLossIndicator | **[LEAKAGE]** Heat loss per m² (used to judge if a heat pump is suitable) |
| GlobalWarmingPotentialValue | Global warming potential of refrigerant in heat pump/cooling (?) |
| SHMainPrimaryEnergy / SHSecPrimaryEnergy | **[LEAKAGE]** Primary energy for main / secondary space heating |
| WHMainPrimaryEnergy / WHSecPrimaryEnergy | **[LEAKAGE]** Primary energy for main / secondary water heating |
| PumpsFansPrimaryEnergy | **[LEAKAGE]** Primary energy for pumps and fans |
| LightingPrimaryEnergy | **[LEAKAGE]** Primary energy for lighting |
| CoolingPrimaryEnergy | **[LEAKAGE]** Primary energy for cooling |
| CHPInputPrimaryEnergy / CHPElecOutputPrimaryEnergy | **[LEAKAGE]** CHP energy in / electricity out |
| RenewPrimaryEnergy1 / 2 / 3, RenewPrimaryEPTot | **[LEAKAGE]** Renewable primary energy (each source and total) |

## 3. Size and Shape of the Home
| Column | Meaning |
|---|---|
| GroundFloorArea(sq m) | **Total** floor area of the home in m² (despite the name; = ground + upper floors) |
| GroundFloorArea / FirstFloorArea / SecondFloorArea / ThirdFloorArea | Floor area of each storey (m²) |
| GroundFloorHeight / FirstFloorHeight / SecondFloorHeight / ThirdFloorHeight | Ceiling height of each storey (m) |
| NoStoreys | Number of storeys |
| WallArea / RoofArea / FloorArea / WindowArea / DoorArea | Total area of each building element (m²) |
| LivingAreaPercent | % of floor area that is the main living room |
| RoomInRoofArea | Floor area of attic rooms (m²) |
| PredominantRoofType | Main roof type, e.g. "Pitch Roof - Insul. on Ceiling" |
| PredominantRoofTypeArea | Area of that main roof type (m²) |

## 4. Insulation and Fabric (how well the walls/roof keep heat in)
*U-value = heat lost through 1 m² for each 1°C difference. **Lower = better insulated.***
| Column | Meaning |
|---|---|
| UValueWall / UValueRoof / UValueFloor / UValueWindow / UvalueDoor | Average U-value of each element |
| GroundFloorUValue | U-value of the ground floor |
| ThermalBridgingFactor | Extra heat loss at joints/edges (0.15 = default) |
| ThermalMassCategory | How much heat the structure stores: Low / Medium / High |
| StructureType | Masonry, timber frame, etc. |
| SuspendedWoodenFloor | Wooden floor over a void: No / Yes (sealed/unsealed) |
| PercentageDraughtStripped | % of windows/doors with draught stripping |
| NoOfSidesSheltered | Sides of the home sheltered by other buildings/trees (0–4) |
| PermeabilityTest | YES/NO: was an air-tightness test done |
| PermeabilityTestResult | Air-tightness test result (lower = more airtight) |
| First/Second/ThirdWallType_Description | Wall construction, e.g. "300mm Cavity", "Stone", "Solid brick" |
| First/Second/ThirdWallDescription | Free-text note typed by the assessor (very messy) |
| First/Second/ThirdWallArea | Area of that wall type (m²) |
| First/Second/ThirdWallUValue | U-value of that wall type |
| First/Second/ThirdWallIsSemiExposed | Yes/No: wall faces an unheated space (e.g. garage) |
| First/Second/ThirdWallAgeBandId | Code for the wall's age band |
| First/Second/ThirdWallTypeId | Code for the wall type |

## 5. Ventilation and Air Leaks
| Column | Meaning |
|---|---|
| NoOfChimneys | Number of open chimneys |
| NoOfOpenFlues | Number of open flues |
| NoOfFansAndVents | Number of extract fans and wall vents |
| NoOfFluelessGasFires | Number of flueless gas fires |
| DraftLobby | YES/NO: draught lobby (porch) at main door |
| VentilationMethod | Natural, extract fans, MVHR (heat recovery), etc. |
| FanPowerManuDeclaredValue | Ventilation fan power from manufacturer |
| HeatExchangerEff | Efficiency of heat-recovery ventilation (%) |

## 6. Space Heating (main heating system)
| Column | Meaning |
|---|---|
| MainSpaceHeatingFuel | Main heating fuel: Heating Oil, Mains Gas, Electricity, etc. |
| HSMainSystemEfficiency | Efficiency of main heating system (%; heat pumps can be >100) |
| HSEffAdjFactor | Adjustment to heating efficiency (e.g. for poor controls) |
| HSSupplHeatFraction | Share of heat from a secondary heater (e.g. 0.1 = 10%) |
| HSSupplSystemEff | Efficiency of the secondary heater (%) |
| SupplSHFuel / SupplHSFuelTypeID | Fuel code of the secondary heater |
| SHRenewableResources | Code for renewables used for space heating (?) |
| TempAdjustment | Temperature adjustment for heating controls |
| HeatSystemControlCat | Heating control category (1 = basic … 3 = best) |
| HeatSystemResponseCat | How fast the heating system responds (category code) |
| CombiBoiler | Type of combi boiler / keep-hot option |
| NoCentralHeatingPumps | Number of central heating pumps |
| CHBoilerThermostatControlled | YES/NO: boiler controlled by a thermostat |
| NoOilBoilerHeatingPumps / OBBoilerThermostatControlled / OBPumpInsideDwelling | Oil boiler pumps, thermostat, pump inside home |
| NoGasBoilerHeatingPumps | Number of gas boiler pumps |
| WarmAirHeatingSystem | YES/NO: warm-air heating system |
| UndergroundHeating | YES/NO: underfloor heating |
| CapacityToWorkAtLowTemperatureLevels | Can the system run at low flow temperatures (heat-pump ready) (?) |

## 7. Water Heating (hot water)
| Column | Meaning |
|---|---|
| MainWaterHeatingFuel | Fuel used for hot water |
| WHMainSystemEff | Efficiency of hot water system (%) |
| WHEffAdjFactor | Adjustment to hot water efficiency |
| SupplWHFuel | Fuel code of secondary water heating |
| WHRenewableResources | Code for renewables used for water heating (?) |
| ElecImmersionInSummer | YES/NO: electric immersion used in summer |
| KeepHotFacility | Keep-hot facility on combi boiler |
| ElecConsumpKeepHot | Electricity used by keep-hot facility |
| WaterStorageVolume | Hot water cylinder size (litres) |
| StorageLosses | YES/NO: cylinder storage losses counted |
| ManuLossFactorAvail | YES/NO: manufacturer's heat-loss figure available |
| DeclaredLossFactor | Manufacturer's declared cylinder heat loss |
| TempFactorUnadj / TempFactorMultiplier | Temperature factors for cylinder losses |
| InsulationType | Cylinder insulation: Loose Jacket / Factory Insulated / None |
| InsulationThickness | Cylinder insulation thickness (mm) |
| PrimaryCircuitLoss | Pipe loss between boiler and cylinder (insulated or not) |
| CombiBoilerAddLoss | Extra loss from a combi boiler |
| CylinderStat | YES/NO: cylinder thermostat |
| CombinedCylinder | YES/NO: combined cylinder |
| VolumeOfPreHeatStore | Volume of pre-heat store (litres) |

## 8. Solar Water Heating
| Column | Meaning |
|---|---|
| SolarHotWaterHeating | YES/NO: solar panels for hot water |
| ApertureArea | Solar collector area (m²) |
| ZeroLossCollectorEff | Collector efficiency |
| CollectorHeatLossCoEff | Collector heat loss coefficient |
| AnnualSolarRadiation | Sun energy reaching the collector per year |
| OvershadingFactor | How shaded the collector is |
| SolarStorageVolume | Solar storage volume (litres) |
| ElectricityConsumption | Electricity used by the solar pump (?) |
| SWHPumpSolarPowered | YES/NO: solar pump powered by PV |
| SolarHeatFraction | Share of hot water from solar |
| SolarSpaceHeatingSystem | YES/NO: solar used for space heating |
| SolarWaterHeatingOrientation / SolarWaterHeatingTiltInDegreesFromHorizontal / SolarWaterHeatingOvershading | Direction, angle and shading of solar collector |

## 9. Group / District Heating and CHP
*Mostly empty: only applies to apartments or estates on shared heating.*
| Column | Meaning |
|---|---|
| ChargingBasisHeatConsumed | YES/NO: residents billed by heat actually used |
| gsdHSSupplHeatFraction / gsdHSSupplSystemEff | Group scheme secondary heat share / efficiency (?) |
| gsdSHRenewableResources / gsdWHRenewableResources | Group scheme renewables for space / water heating (?) |
| DistLossFactor | Heat lost in the shared heating pipes |
| HeatLossFromDistributionSystemOutsideDwelling | Pipe heat loss outside the home |
| CHPUnitHeatFraction | Share of heat from Combined Heat and Power (CHP) |
| CHPSystemType / CHPSystemTypeDescription | Type of CHP system |
| CHPElecEff / CHPHeatEff | CHP electrical / heat efficiency |
| CHPFuelType | CHP fuel |
| GroupHeatingCO2EQEmissionsFactor | CO₂ factor of the group heating |
| GroupHeatingNonRenewablePEF / GroupHeatingRenewablePEF | Primary energy factors (non-renewable / renewable) |
| First/Second/ThirdBoilerFuelType | Fuel of each group heating boiler |
| First/Second/ThirdHeatGenPlantEff | Efficiency of each group heating plant |
| First/Second/ThirdPercentageHeat | % of heat from each plant |

## 10. Other Energy Sources (special renewables, up to 3)
| Column | Meaning |
|---|---|
| First/Second/ThirdEnergyTypeId | Code of the extra energy source |
| First/Second/ThirdEnergyType_Description | Name, e.g. "Renewable Thermal" |
| First/Second/ThirdEnerProdComment | Assessor note on energy produced |
| First/Second/ThirdEnerProdDelivered | Energy produced (kWh/yr) |
| First/Second/ThirdPartLTotalContribution | Contribution towards Part L renewables target |
| First/Second/ThirdEnerProdConvFactor / ...EnerProdCO2EmissionFactor | Primary energy and CO₂ factors for energy produced |
| First/Second/ThirdEnerConsumedComment | Assessor note on energy consumed |
| First/Second/ThirdEnerConsumedDelivered | Energy consumed (kWh/yr) |
| First/Second/ThirdEnerConsumedConvFactor / ...EnerConsumedCO2EmissionFactor | Primary energy and CO₂ factors for energy consumed |

## 11. Solar PV (electric panels) and Wind
| Column | Meaning |
|---|---|
| First…FifthSolarPVNoPanels | Number of PV panels in each array (up to 5 arrays) |
| First…FifthSolarPVPeakPowerPerPanel | Peak power per panel (kW) |
| First…FifthSolarPVOrientation / …Tilt / …Overshading | Direction, angle and shading of each array |
| IsSolarPVBatteryPresent | YES/NO: home battery |
| SolarBatteryCapacity | Battery size (kWh) |
| SolarPVEnergyOutput | Electricity made by PV per year (kWh) |
| WindTurbineEnergyOutput | Electricity made by wind turbine per year (kWh) |
| First/Second/ThirdWindTurbineRotorDiameter / …HubHeight / …TerrainType | Size, height and location type of each turbine |

## 12. NZEB (Nearly Zero Energy Building) Flags
| Column | Meaning |
|---|---|
| IsPropertyExemptFromZeb | Home exempt from NZEB rules (?) |
| OverrideIsFossilFuelUsedOnSite | Assessor override: fossil fuel used on site (?) |
| IsSystemApplicable | System applicability flag (?) |

---

### Key notes for modelling
1. **Targets:** `BerRating` (regression) and `EnergyRating` (classification).
2. **Never use [LEAKAGE] columns as inputs.** They come from the same calculation as the target.
3. `GroundFloorArea(sq m)` is the **total** floor area (it equals GroundFloorArea + FirstFloorArea + …).
4. Sections 8–12 are **mostly empty** (only a few homes have solar, CHP, wind etc.). Check % missing before using them.
5. `CountyName` mixes counties and Dublin postal districts. We need a county lookup to join with the PPR data.

#### IT is so large to understand so i have a solution-- a idea 
#lets Normalize the table

In [38]:
# The file has no ID column, so we make one: 1, 2, 3, ...
ber['ber_id'] = range(1, len(ber) + 1)

# Remove extra spaces from text we will use in lookup tables
ber['CountyName'] = ber['CountyName'].str.strip()
ber['DwellingTypeDescr'] = ber['DwellingTypeDescr'].str.strip()
ber['MainSpaceHeatingFuel'] = ber['MainSpaceHeatingFuel'].str.strip()
ber['MainWaterHeatingFuel'] = ber['MainWaterHeatingFuel'].str.strip()

ber[['ber_id', 'CountyName', 'DwellingTypeDescr']].head()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\3540260906.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ber['ber_id'] = range(1, len(ber) + 1)

   ber_id   CountyName    DwellingTypeDescr
0       1  Co. Kildare       Detached house
1       2  Co. Kildare       Detached house
2       3  Co. Kildare       Detached house
3       4     Co. Cork  Semi-detached house
4       5    Co. Laois       Detached house

In [39]:
# County lookup: each county name stored once, with its own id
county_names = sorted(ber['CountyName'].dropna().unique())
county = pd.DataFrame({'county_id': range(1, len(county_names) + 1),
                       'CountyName': county_names})

# Dwelling type lookup
type_names = sorted(ber['DwellingTypeDescr'].dropna().unique())
dwelling_type = pd.DataFrame({'dwelling_type_id': range(1, len(type_names) + 1),
                              'DwellingTypeDescr': type_names})

# Fuel lookup (space heating and water heating use the same fuel names)
all_fuels = pd.concat([ber['MainSpaceHeatingFuel'], ber['MainWaterHeatingFuel']])
fuel_names = sorted(all_fuels.dropna().unique())
fuel = pd.DataFrame({'fuel_id': range(1, len(fuel_names) + 1),
                     'FuelName': fuel_names})

print(county.shape, dwelling_type.shape, fuel.shape)
county.head()

(52, 2) (10, 2) (18, 2)

   county_id   CountyName
0          1   Co. Carlow
1          2    Co. Cavan
2          3    Co. Clare
3          4     Co. Cork
4          5  Co. Donegal

In [40]:
# ---------- assessment (main table) ----------
assessment = ber[['ber_id', 'CountyName', 'DwellingTypeDescr', 'Year_of_Construction',
                  'TypeofRating', 'PurposeOfRating', 'DateOfAssessment', 'MultiDwellingMPRN',
                  'TGDLEdition', 'SA_Code', 'prob_smarea_error_0corr', 'prob_smarea_error_100corr']].copy()

# Replace names with ids from the lookup tables
county_map = dict(zip(county['CountyName'], county['county_id']))
type_map = dict(zip(dwelling_type['DwellingTypeDescr'], dwelling_type['dwelling_type_id']))
assessment['county_id'] = assessment['CountyName'].map(county_map)
assessment['dwelling_type_id'] = assessment['DwellingTypeDescr'].map(type_map)
assessment = assessment.drop(columns=['CountyName', 'DwellingTypeDescr'])

# ---------- results (targets + leakage columns) ----------
results = ber[['ber_id', 'BerRating', 'EnergyRating', 'CO2Rating', 'MPCDERValue', 'RER',
               'RenewEPnren', 'RenewEPren', 'CPC', 'EPC', 'GlobalWarmingPotentialValue',
               'HeatLossIndicator', 'SHMainPrimaryEnergy', 'SHSecPrimaryEnergy',
               'WHMainPrimaryEnergy', 'WHSecPrimaryEnergy', 'PumpsFansPrimaryEnergy',
               'LightingPrimaryEnergy', 'CoolingPrimaryEnergy', 'CHPInputPrimaryEnergy',
               'CHPElecOutputPrimaryEnergy', 'RenewPrimaryEnergy1', 'RenewPrimaryEnergy2',
               'RenewPrimaryEnergy3', 'RenewPrimaryEPTot']].copy()

# ---------- geometry ----------
geometry = ber[['ber_id', 'GroundFloorArea(sq m)', 'NoStoreys', 'WallArea', 'RoofArea',
                'FloorArea', 'WindowArea', 'DoorArea', 'LivingAreaPercent', 'RoomInRoofArea',
                'PredominantRoofType', 'PredominantRoofTypeArea']].copy()

# ---------- fabric ----------
fabric = ber[['ber_id', 'UValueWall', 'UValueRoof', 'UValueFloor', 'UValueWindow', 'UvalueDoor',
              'GroundFloorUValue', 'ThermalBridgingFactor', 'ThermalMassCategory', 'StructureType',
              'SuspendedWoodenFloor', 'PercentageDraughtStripped', 'NoOfSidesSheltered',
              'PermeabilityTest', 'PermeabilityTestResult']].copy()

# ---------- ventilation ----------
ventilation = ber[['ber_id', 'NoOfChimneys', 'NoOfOpenFlues', 'NoOfFansAndVents',
                   'NoOfFluelessGasFires', 'DraftLobby', 'VentilationMethod',
                   'FanPowerManuDeclaredValue', 'HeatExchangerEff']].copy()

# ---------- space heating ----------
space_heating = ber[['ber_id', 'MainSpaceHeatingFuel', 'HSMainSystemEfficiency', 'HSEffAdjFactor',
                     'HSSupplHeatFraction', 'HSSupplSystemEff', 'SupplSHFuel', 'SupplHSFuelTypeID',
                     'SHRenewableResources', 'TempAdjustment', 'HeatSystemControlCat',
                     'HeatSystemResponseCat', 'NoCentralHeatingPumps', 'CHBoilerThermostatControlled',
                     'NoOilBoilerHeatingPumps', 'OBBoilerThermostatControlled', 'OBPumpInsideDwelling',
                     'NoGasBoilerHeatingPumps', 'WarmAirHeatingSystem', 'UndergroundHeating',
                     'CombiBoiler', 'CapacityToWorkAtLowTemperatureLevels']].copy()

fuel_map = dict(zip(fuel['FuelName'], fuel['fuel_id']))
space_heating['main_fuel_id'] = space_heating['MainSpaceHeatingFuel'].map(fuel_map)
space_heating = space_heating.drop(columns=['MainSpaceHeatingFuel'])

# ---------- water heating ----------
water_heating = ber[['ber_id', 'MainWaterHeatingFuel', 'WHMainSystemEff', 'WHEffAdjFactor',
                     'SupplWHFuel', 'WHRenewableResources', 'StorageLosses', 'ManuLossFactorAvail',
                     'ElecImmersionInSummer', 'KeepHotFacility', 'WaterStorageVolume',
                     'DeclaredLossFactor', 'TempFactorUnadj', 'TempFactorMultiplier',
                     'InsulationType', 'InsulationThickness', 'PrimaryCircuitLoss',
                     'CombiBoilerAddLoss', 'ElecConsumpKeepHot', 'CylinderStat',
                     'CombinedCylinder', 'VolumeOfPreHeatStore']].copy()

water_heating['main_fuel_id'] = water_heating['MainWaterHeatingFuel'].map(fuel_map)
water_heating = water_heating.drop(columns=['MainWaterHeatingFuel'])

# ---------- solar water ----------
solar_water = ber[['ber_id', 'SolarHotWaterHeating', 'ApertureArea', 'ZeroLossCollectorEff',
                   'CollectorHeatLossCoEff', 'AnnualSolarRadiation', 'OvershadingFactor',
                   'SolarStorageVolume', 'ElectricityConsumption', 'SWHPumpSolarPowered',
                   'SolarHeatFraction', 'SolarSpaceHeatingSystem', 'SolarWaterHeatingOrientation',
                   'SolarWaterHeatingTiltInDegreesFromHorizontal', 'SolarWaterHeatingOvershading']].copy()

# ---------- group heating ----------
group_heating = ber[['ber_id', 'ChargingBasisHeatConsumed', 'gsdHSSupplHeatFraction',
                     'gsdHSSupplSystemEff', 'DistLossFactor', 'CHPUnitHeatFraction', 'CHPSystemType',
                     'CHPSystemTypeDescription', 'GroupHeatingCO2EQEmissionsFactor',
                     'GroupHeatingNonRenewablePEF', 'GroupHeatingRenewablePEF',
                     'HeatLossFromDistributionSystemOutsideDwelling', 'CHPElecEff', 'CHPHeatEff',
                     'CHPFuelType', 'gsdSHRenewableResources', 'gsdWHRenewableResources']].copy()

# ---------- NZEB + renewables summary ----------
nzeb_renewables = ber[['ber_id', 'IsSolarPVBatteryPresent', 'SolarBatteryCapacity',
                       'SolarPVEnergyOutput', 'WindTurbineEnergyOutput', 'IsPropertyExemptFromZeb',
                       'OverrideIsFossilFuelUsedOnSite', 'IsSystemApplicable']].copy()

print('One-to-one tables created')

One-to-one tables created

In [41]:
def stack_group(numbers, column_endings, new_names, number_name):
    """Turn columns like FirstWallArea, SecondWallArea... into rows."""
    pieces = []
    for n in numbers:
        # build the real column names, e.g. 'First' + 'WallArea' = 'FirstWallArea'
        old_cols = []
        for ending in column_endings:
            old_cols.append(n + ending)

        part = ber[['ber_id'] + old_cols].copy()
        part.columns = ['ber_id'] + new_names   # give simple names
        part[number_name] = n                   # remember which one it was (First, Second, ...)
        pieces.append(part)

    return pd.concat(pieces, ignore_index=True)


# ---------- floors ----------
floors = stack_group(['Ground', 'First', 'Second', 'Third'],
                     ['FloorArea', 'FloorHeight'],
                     ['floor_area', 'floor_height'], 'floor_no')
floors['floor_area'] = pd.to_numeric(floors['floor_area'], errors='coerce')
floors = floors[floors['floor_area'] > 0]          # keep only floors that exist

# ---------- walls ----------
walls = stack_group(['First', 'Second', 'Third'],
                    ['WallType_Description', 'WallDescription', 'WallArea', 'WallUValue',
                     'WallIsSemiExposed', 'WallAgeBandId', 'WallTypeId'],
                    ['wall_type', 'wall_note', 'wall_area', 'wall_uvalue',
                     'is_semi_exposed', 'age_band_id', 'wall_type_id'], 'wall_no')
walls['wall_area'] = pd.to_numeric(walls['wall_area'], errors='coerce')
walls = walls[walls['wall_area'] > 0]

# ---------- other energy sources ----------
other_energy = stack_group(['First', 'Second', 'Third'],
                           ['EnergyTypeId', 'EnergyType_Description', 'EnerProdComment',
                            'EnerProdDelivered', 'PartLTotalContribution', 'EnerProdConvFactor',
                            'EnerProdCO2EmissionFactor', 'EnerConsumedComment',
                            'EnerConsumedDelivered', 'EnerConsumedConvFactor',
                            'EnerConsumedCO2EmissionFactor'],
                           ['energy_type_id', 'energy_type', 'prod_comment', 'prod_delivered',
                            'partL_contribution', 'prod_conv_factor', 'prod_co2_factor',
                            'consumed_comment', 'consumed_delivered', 'consumed_conv_factor',
                            'consumed_co2_factor'], 'source_no')
other_energy['prod_delivered'] = pd.to_numeric(other_energy['prod_delivered'], errors='coerce')
other_energy['consumed_delivered'] = pd.to_numeric(other_energy['consumed_delivered'], errors='coerce')
other_energy = other_energy[(other_energy['prod_delivered'] > 0) | (other_energy['consumed_delivered'] > 0)]

# ---------- group heating boilers ----------
group_boilers = stack_group(['First', 'Second', 'Third'],
                            ['BoilerFuelType', 'HeatGenPlantEff', 'PercentageHeat'],
                            ['boiler_fuel', 'plant_efficiency', 'percentage_heat'], 'boiler_no')
group_boilers = group_boilers[group_boilers['boiler_fuel'].notna()]

# ---------- solar PV arrays ----------
solar_pv = stack_group(['First', 'Second', 'Third', 'Fourth', 'Fifth'],
                       ['SolarPVNoPanels', 'SolarPVPeakPowerPerPanel', 'SolarPVOrientation',
                        'SolarPVTilt', 'SolarPVOvershading'],
                       ['no_panels', 'peak_power_per_panel', 'orientation', 'tilt', 'overshading'],
                       'array_no')
solar_pv['no_panels'] = pd.to_numeric(solar_pv['no_panels'], errors='coerce')
solar_pv = solar_pv[solar_pv['no_panels'] > 0]

# ---------- wind turbines ----------
wind_turbines = stack_group(['First', 'Second', 'Third'],
                            ['WindTurbineRotorDiameter', 'WindTurbineHubHeight', 'WindTurbineTerrainType'],
                            ['rotor_diameter', 'hub_height', 'terrain_type'], 'turbine_no')
wind_turbines['rotor_diameter'] = pd.to_numeric(wind_turbines['rotor_diameter'], errors='coerce')
wind_turbines = wind_turbines[wind_turbines['rotor_diameter'] > 0]

print('One-to-many tables created')

One-to-many tables created

In [42]:
# Every original column should be in exactly one table
used = ['ber_id']
for t in [assessment, results, geometry, fabric, ventilation, space_heating,
          water_heating, solar_water, group_heating, nzeb_renewables]:
    used = used + list(t.columns)

# Names we replaced with ids or turned into rows
used = used + ['CountyName', 'DwellingTypeDescr', 'MainSpaceHeatingFuel', 'MainWaterHeatingFuel']
for col in ber.columns:
    for word in ['Floor', 'Wall', 'Ener', 'EnergyType', 'PartLTotal', 'Boiler', 'HeatGenPlant',
                 'PercentageHeat', 'SolarPV', 'WindTurbine']:
        if word in col:
            used.append(col)

leftover = []
for col in ber.columns:
    if col not in used:
        leftover.append(col)

print('Columns not placed in any table:', leftover)   # should be []

Columns not placed in any table: []

In [43]:
tables = {
    'county': county, 'dwelling_type': dwelling_type, 'fuel': fuel,
    'assessment': assessment, 'results': results, 'geometry': geometry, 'fabric': fabric,
    'ventilation': ventilation, 'space_heating': space_heating, 'water_heating': water_heating,
    'solar_water': solar_water, 'group_heating': group_heating, 'nzeb_renewables': nzeb_renewables,
    'floors': floors, 'walls': walls, 'other_energy': other_energy,
    'group_boilers': group_boilers, 'solar_pv': solar_pv, 'wind_turbines': wind_turbines,
}

for name in tables:
    print('=' * 60)
    print('TABLE:', name, '| shape:', tables[name].shape)
    display(tables[name].head())

============================================================
TABLE: county | shape: (52, 2)

   county_id   CountyName
0          1   Co. Carlow
1          2    Co. Cavan
2          3    Co. Clare
3          4     Co. Cork
4          5  Co. Donegal

============================================================
TABLE: dwelling_type | shape: (10, 2)

   dwelling_type_id       DwellingTypeDescr
0                 1               Apartment
1                 2       Basement Dwelling
2                 3          Detached house
3                 4    End of terrace house
4                 5  Ground-floor apartment

============================================================
TABLE: fuel | shape: (18, 2)

   fuel_id                        FuelName
0        1                      Anthracite
1        2  Biodiesel from renewable sourc
2        3  Bioethanol from renewable sour
3        4                     Bottled LPG
4        5    Bulk LPG (propane or butane)

============================================================
TABLE: assessment | shape: (569058, 12)

,ber_id,Year_of_Construction,TypeofRating,PurposeOfRating,DateOfAssessment,MultiDwellingMPRN,TGDLEdition,SA_Code,prob_smarea_error_0corr,prob_smarea_error_100corr,county_id,dwelling_type_id
0,1,2000,Existing,Private Letting,2021-01-01,YES,0,NaN,NaN,NaN,9,3
1,2,2000,Existing,Private Letting,2021-01-01,YES,0,NaN,NaN,NaN,9,3
2,3,2000,Existing,Private Letting,2021-01-01,YES,0,NaN,NaN,NaN,9,3
3,4,1930,Existing,Major Renovation,2021-01-01,NO,0,NaN,NaN,NaN,4,9
4,5,1850,Existing,Sale,2021-01-02,NO,0,NaN,NaN,NaN,11,3

============================================================
TABLE: results | shape: (569058, 25)

,ber_id,BerRating,EnergyRating,CO2Rating,MPCDERValue,RER,RenewEPnren,RenewEPren,CPC,EPC,GlobalWarmingPotentialValue,HeatLossIndicator,SHMainPrimaryEnergy,SHSecPrimaryEnergy,WHMainPrimaryEnergy,WHSecPrimaryEnergy,PumpsFansPrimaryEnergy,LightingPrimaryEnergy,CoolingPrimaryEnergy,CHPInputPrimaryEnergy,CHPElecOutputPrimaryEnergy,RenewPrimaryEnergy1,RenewPrimaryEnergy2,RenewPrimaryEnergy3,RenewPrimaryEPTot
0,1,339.72,E1,79.15,65.66,0.000,8275.79,0.0,1.217,1.056,NaN,NaN,4324.60,0.00,1932.40,929.89,1348.62,178.41,NaN,0.0,0.0,0.0,0.0,0.0,8275.79
1,2,290.10,D2,68.41,51.77,0.000,11375.40,0.0,1.314,1.136,NaN,NaN,7108.39,0.00,2057.21,989.85,1453.54,232.77,NaN,0.0,0.0,0.0,0.0,0.0,11375.40
2,3,290.33,D2,68.47,51.81,0.000,11385.00,0.0,1.314,1.136,NaN,NaN,7118.03,0.00,2057.21,989.85,1453.54,232.77,NaN,0.0,0.0,0.0,0.0,0.0,11385.00
3,4,24.52,A1,5.75,47.31,0.764,3532.67,11435.6,0.184,0.162,NaN,NaN,2717.66,1059.47,2849.31,0.00,867.54,638.62,NaN,0.0,0.0,0.0,0.0,0.0,14968.30
4,5,1200.95,G,390.47,121.35,0.000,84803.70,0.0,8.758,5.521,NaN,NaN,60484.50,10101.50,9330.84,3252.07,1875.79,1291.29,NaN,0.0,0.0,0.0,0.0,0.0,84803.70

============================================================
TABLE: geometry | shape: (569058, 12)

,ber_id,GroundFloorArea(sq m),NoStoreys,WallArea,RoofArea,FloorArea,WindowArea,DoorArea,LivingAreaPercent,RoomInRoofArea,PredominantRoofType,PredominantRoofTypeArea
0,1,25.65,1,50.75,25.65,25.65,3.47,1.85,45.61,0.0,Pitch Roof-Insul.on Rafter,25.65
1,2,40.82,1,59.83,40.82,40.82,8.87,3.70,42.33,0.0,Pitch Roof-Insul.on Rafter,40.82
2,3,40.82,1,59.83,40.82,40.82,8.87,3.70,43.04,0.0,Pitch Roof-Insul.on Rafter,40.82
3,4,147.70,2,114.06,99.66,105.30,30.56,1.85,18.35,0.0,Pitch Roof-Insul.on Ceiling,42.40
4,5,71.89,1,99.73,71.89,71.89,6.40,1.75,25.59,0.0,Pitch Roof-Insul.on Ceiling,71.89

============================================================
TABLE: fabric | shape: (569058, 15)

,ber_id,UValueWall,UValueRoof,UValueFloor,UValueWindow,UvalueDoor,GroundFloorUValue,ThermalBridgingFactor,ThermalMassCategory,StructureType,SuspendedWoodenFloor,PercentageDraughtStripped,NoOfSidesSheltered,PermeabilityTest,PermeabilityTestResult
0,1,0.55,0.36,0.52,2.80,3.00,0.0,0.15,Medium,Masonry,No,100.0,2.0,NO,0.0
1,2,0.55,0.36,0.49,2.80,3.00,0.0,0.15,Medium,Masonry,No,100.0,2.0,NO,0.0
2,3,0.55,0.36,0.49,2.80,3.00,0.0,0.15,Medium,Masonry,No,100.0,2.0,NO,0.0
3,4,0.24,0.18,0.11,1.25,1.40,0.0,0.15,Medium,Masonry,No,100.0,2.0,NO,0.0
4,5,2.10,2.30,0.94,4.48,1.71,0.0,0.15,High,Masonry,No,13.0,1.0,NO,0.0

============================================================
TABLE: ventilation | shape: (569058, 9)

,ber_id,NoOfChimneys,NoOfOpenFlues,NoOfFansAndVents,NoOfFluelessGasFires,DraftLobby,VentilationMethod,FanPowerManuDeclaredValue,HeatExchangerEff
0,1,0.0,0.0,1.0,0.0,YES,Natural vent.,0.00,0.0
1,2,0.0,0.0,2.0,0.0,YES,Natural vent.,0.00,0.0
2,3,0.0,0.0,2.0,0.0,YES,Natural vent.,0.00,0.0
3,4,0.0,1.0,0.0,0.0,NO,Bal.whole mech.vent heat recvr,0.63,90.0
4,5,2.0,1.0,0.0,0.0,YES,Natural vent.,0.00,0.0

============================================================
TABLE: space_heating | shape: (569058, 22)

,ber_id,HSMainSystemEfficiency,HSEffAdjFactor,HSSupplHeatFraction,HSSupplSystemEff,SupplSHFuel,SupplHSFuelTypeID,SHRenewableResources,TempAdjustment,HeatSystemControlCat,HeatSystemResponseCat,NoCentralHeatingPumps,CHBoilerThermostatControlled,NoOilBoilerHeatingPumps,OBBoilerThermostatControlled,OBPumpInsideDwelling,NoGasBoilerHeatingPumps,WarmAirHeatingSystem,UndergroundHeating,CombiBoiler,CapacityToWorkAtLowTemperatureLevels,main_fuel_id
0,1,85.60,0.95,0.0,0.0,1.0,NaN,1.0,0.0,1,1,1,YES,1,NO,NO,0,NO,NO,None,NaN,7.0
1,2,85.60,0.95,0.0,0.0,1.0,NaN,1.0,0.0,1,1,1,YES,1,NO,NO,0,NO,NO,None,NaN,7.0
2,3,85.60,0.95,0.0,0.0,1.0,NaN,1.0,0.0,1,1,1,YES,1,NO,NO,0,NO,NO,None,NaN,7.0
3,4,464.67,1.00,0.1,77.0,8.0,NaN,1.0,0.0,3,3,1,YES,0,NO,NO,0,NO,NO,None,NaN,6.0
4,5,45.00,1.00,0.1,30.0,15.0,NaN,1.0,0.6,1,2,1,NO,0,NO,NO,0,NO,NO,None,NaN,14.0

============================================================
TABLE: water_heating | shape: (569058, 22)

,ber_id,WHMainSystemEff,WHEffAdjFactor,SupplWHFuel,WHRenewableResources,StorageLosses,ManuLossFactorAvail,ElecImmersionInSummer,KeepHotFacility,WaterStorageVolume,DeclaredLossFactor,TempFactorUnadj,TempFactorMultiplier,InsulationType,InsulationThickness,PrimaryCircuitLoss,CombiBoilerAddLoss,ElecConsumpKeepHot,CylinderStat,CombinedCylinder,VolumeOfPreHeatStore,main_fuel_id
0,1,85.60,0.95,28.0,1.0,YES,NO,YES,inapplicable,110.0,0.0,0.6,1.3,Factory Insulated,30.0,Boiler with uninsulated primar,0.0,0.0,NO,NO,NaN,7.0
1,2,85.60,0.95,28.0,1.0,YES,NO,YES,inapplicable,110.0,0.0,0.6,1.3,Factory Insulated,30.0,Boiler with uninsulated primar,0.0,0.0,NO,NO,NaN,7.0
2,3,85.60,0.95,28.0,1.0,YES,NO,YES,inapplicable,110.0,0.0,0.6,1.3,Factory Insulated,30.0,Boiler with uninsulated primar,0.0,0.0,NO,NO,NaN,7.0
3,4,257.63,1.00,1.0,1.0,YES,YES,NO,inapplicable,230.0,1.4,0.6,0.9,None,0.0,Boiler with uninsulated primar,0.0,0.0,NO,NO,NaN,6.0
4,5,45.00,1.00,28.0,1.0,YES,NO,YES,inapplicable,95.0,0.0,0.6,1.3,None,0.0,Boiler with uninsulated primar,0.0,0.0,NO,NO,NaN,14.0

============================================================
TABLE: solar_water | shape: (569058, 15)

,ber_id,SolarHotWaterHeating,ApertureArea,ZeroLossCollectorEff,CollectorHeatLossCoEff,AnnualSolarRadiation,OvershadingFactor,SolarStorageVolume,ElectricityConsumption,SWHPumpSolarPowered,SolarHeatFraction,SolarSpaceHeatingSystem,SolarWaterHeatingOrientation,SolarWaterHeatingTiltInDegreesFromHorizontal,SolarWaterHeatingOvershading
0,1,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN
1,2,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN
2,3,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN
3,4,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN
4,5,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN

============================================================
TABLE: group_heating | shape: (569058, 17)

,ber_id,ChargingBasisHeatConsumed,gsdHSSupplHeatFraction,gsdHSSupplSystemEff,DistLossFactor,CHPUnitHeatFraction,CHPSystemType,CHPSystemTypeDescription,GroupHeatingCO2EQEmissionsFactor,GroupHeatingNonRenewablePEF,GroupHeatingRenewablePEF,HeatLossFromDistributionSystemOutsideDwelling,CHPElecEff,CHPHeatEff,CHPFuelType,gsdSHRenewableResources,gsdWHRenewableResources
0,1,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

============================================================
TABLE: nzeb_renewables | shape: (569058, 8)

,ber_id,IsSolarPVBatteryPresent,SolarBatteryCapacity,SolarPVEnergyOutput,WindTurbineEnergyOutput,IsPropertyExemptFromZeb,OverrideIsFossilFuelUsedOnSite,IsSystemApplicable
0,1,0.0,0.0,0.00,0.0,NaN,NaN,NaN
1,2,0.0,0.0,0.00,0.0,NaN,NaN,NaN
2,3,0.0,0.0,0.00,0.0,NaN,NaN,NaN
3,4,0.0,0.0,2169.06,0.0,NaN,NaN,NaN
4,5,0.0,0.0,0.00,0.0,NaN,NaN,NaN

============================================================
TABLE: floors | shape: (975905, 4)

   ber_id  floor_area  floor_height floor_no
0       1       25.65          2.37   Ground
1       2       40.82          2.38   Ground
2       3       40.82          2.38   Ground
3       4      105.30          2.46   Ground
4       5       71.89          2.86   Ground

============================================================
TABLE: walls | shape: (952212, 9)

,ber_id,wall_type,wall_note,wall_area,wall_uvalue,is_semi_exposed,age_band_id,wall_type_id,wall_no
0,1,Unknown,NaN,50.75,0.55,No,9.0,10.0,First
1,2,Unknown,NaN,59.83,0.55,No,9.0,10.0,First
2,3,Unknown,NaN,59.83,0.55,No,9.0,10.0,First
3,4,Other,NEW WALLS 150MM PUMPED CAVITY,63.65,0.21,No,3.0,9.0,First
4,5,Stone,NaN,99.73,2.10,No,1.0,1.0,First

============================================================
TABLE: other_energy | shape: (124817, 13)

,ber_id,energy_type_id,energy_type,prod_comment,prod_delivered,partL_contribution,prod_conv_factor,prod_co2_factor,consumed_comment,consumed_delivered,consumed_conv_factor,consumed_co2_factor,source_no
3,4,2.0,Renewable Electrical,PV,2169.06,2169.06,2.08,0.409, ,0.0,0.0,0.0,First
7,8,2.0,Renewable Electrical,PV 310 x 13 x south @ 30 deg +,5000.66,0.0,2.08,0.409, ,0.0,0.0,0.0,First
8,9,2.0,Renewable Electrical,Photovoltaic Electricity,1377.47,1377.47,2.08,0.409, ,0.0,0.0,0.0,First
10,11,2.0,Renewable Electrical,6 no. 310W S facing,1595.00,1595.0,2.08,0.409, ,0.0,0.0,0.0,First
11,12,2.0,Renewable Electrical,6 no. 300W S facing,1543.00,1543.0,2.08,0.409, ,0.0,0.0,0.0,First

============================================================
TABLE: group_boilers | shape: (37003, 5)

     ber_id  boiler_fuel  plant_efficiency  percentage_heat boiler_no
275     276          0.0               0.0              0.0     First
279     280          0.0               0.0              0.0     First
416     417          0.0               0.0              0.0     First
597     598          0.0               0.0              0.0     First
826     827          0.0               0.0              0.0     First

============================================================
TABLE: solar_pv | shape: (182, 7)

,ber_id,no_panels,peak_power_per_panel,orientation,tilt,overshading,array_no
262068,262069,2.75949,13490.40,1923.63,3174.11,0.0,First
466082,466083,1.02245,1821.29,0.0,2140.44,0.0,First
563581,563582,3.00000,435.00,North,35.00,None or very little,First
563583,563584,8.00000,420.00,SE/SW,30.00,Modest,First
563586,563587,12.00000,450.00,South,30.00,None or very little,First

============================================================
TABLE: wind_turbines | shape: (1, 5)

         ber_id  rotor_diameter  hub_height terrain_type turbine_no
1553499  415384         2.14513     6400.77      2372.43      Third

In [50]:
# The folder where we want to save the files (written out in full)
folder = r'C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\processed_dataset\housing_energy_dataset'

# Save each table as its own CSV file inside that folder
for name in tables:
    csv_path = folder + '\\Final_datset_' + name + '.csv'
    tables[name].to_csv(csv_path, index=False)
    print('Saved:', csv_path, tables[name].shape)

print('All tables saved!')

Saved: C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\processed_dataset\housing_energy_dataset\Final_datset_county.csv (52, 2)
Saved: C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\processed_dataset\housing_energy_dataset\Final_datset_dwelling_type.csv (10, 2)
Saved: C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\processed_dataset\housing_energy_dataset\Final_datset_fuel.csv (18, 2)
Saved: C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\processed_dataset\housing_energy_dataset\Final_datset_assessment.csv (569058, 12)
Saved: C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\processed_dataset\housing_energy_dataset\Final_datset_results.csv (569058, 25)
Saved: C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\processed_dataset\housing_energy_dataset\Final_datset_geometry.csv (569058, 12)
Saved: C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\processed_dataset\housing_energy_dataset\Final_datset_fabric.csv (569058, 15)
Saved: C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\processed_dataset\housing_energy_dataset\Final_datset_ventilation.csv (569058, 9)
Saved: C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\processed_dataset\housing_energy_dataset\Final_datset_space_heating.csv (569058, 22)
Saved: C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\processed_dataset\housing_energy_dataset\Final_datset_water_heating.csv (569058, 22)
Saved: C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\processed_dataset\housing_energy_dataset\Final_datset_solar_water.csv (569058, 15)
Saved: C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\processed_dataset\housing_energy_dataset\Final_datset_group_heating.csv (569058, 17)
Saved: C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\processed_dataset\housing_energy_dataset\Final_datset_nzeb_renewables.csv (569058, 8)
Saved: C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\processed_dataset\housing_energy_dataset\Final_datset_floors.csv (975905, 4)
Saved: C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\processed_dataset\housing_energy_dataset\Final_datset_walls.csv (952212, 9)
Saved: C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\processed_dataset\housing_energy_dataset\Final_datset_other_energy.csv (124817, 13)
Saved: C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\processed_dataset\housing_energy_dataset\Final_datset_group_boilers.csv (37003, 5)
Saved: C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\processed_dataset\housing_energy_dataset\Final_datset_solar_pv.csv (182, 7)
Saved: C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\processed_dataset\housing_energy_dataset\Final_datset_wind_turbines.csv (1, 5)
All tables saved!